### ISSUE TITLE
Async Resolvers

### ISSUE THREAD

**Issue by oexza** [graphql-java/graphql-java-tools#1]
With the introduction of this project  https://github.com/bmsantos/graphql-java-async it would be nice to be able to provide nonblocking async resolvers.

**Comment by apottere** [comment]
I was under the impression that graphql-java-async just used a new `ExecutionContext` to get async queries working, which should work fine.

Once that project is released to central I'll make sure the two libraries work together, though.

**Comment by oexza** [comment]
Candidly i had not tried my hands on the project at the time, i just tried it out today and i can confirm that it works with resolvers returning `CompletionStage<T>.` Great work on this project! Thanks.

Peace.

**Comment by oexza** [comment]
It appears version 3.x has added changes that break the previous compatibity with async resolvers methods.

**Comment by apottere** [comment]
Would you mind sending a stacktrace?  I think I might know what's going on, but more info would help.

**Comment by oexza** [comment]
here:

`Constructor threw exception; nested exception is com.coxautodev.graphq
l.tools.ResolverError: No method found with any of the following signatures (in priority order):
  java.util.concurrent.CompletableFuture.ipAddress( [, graphql.schema.DataFetchingEnvironment])
  java.util.concurrent.CompletableFuture.getIpAddress( [, graphql.schema.DataFetchingEnvironment])

`

**Comment by apottere** [comment]
This is released in `3.0.2`.
