### ISSUE TITLE
Support of Reactor's types like Mono<T> and Flux<T>?

### ISSUE THREAD

**Issue by sp00m** [graphql-java/graphql-java-tools#103]
I'm building a Spring Boot 2 project with Reactive Web (Spring WebFlux), which relies on [Reactor](https://projectreactor.io/). My services are thus returning `Mono<T>`s and `Flux<T>`s.

The problem is that I can't manage to make my `GraphQLSchema` handle those types correctly.

---

For example, say I have the following schema:

```text
type Query {
  article(
    id: Long!
  ): Article!
}

type Article {
  id: Long!
  name: String!
}
```

And the following `QueryResolver`:

```java
public class QueryResolver implements GraphQLQueryResolver {
    
  private final ArticleService articleService;

  public QueryResolver(ArticleService articleService) {
    this.articleService = articleService;
  }

  public Mono<Article> getArticle(long id) {
    return articleService.findOneById(id);
  }
    
}
```

Building the schema:

```java
GraphQLSchema schema = SchemaParser.newParser()
  .file("schema.graphqls")
  .resolvers(queryResolver)
  .build()
  .makeExecutableSchema();
GraphQL build = GraphQL.newGraphQL(schema).build();
```

When running a query:

```java
ExecutionResult executionResult = build.execute("...");
```

I catch the following exception:

```text
TypeClassMatcher$RawClassRequiredForGraphQLMappingException: Type reactor.core.publisher.Mono<my.pkg.Article> cannot be mapped to a GraphQL type!  Since GraphQL-Java deals with erased types at runtime, only non-parameterized classes can represent a GraphQL type.  This allows for reverse-lookup by java class in interfaces and union types.
```

---

I then tried to register a `SchemaParserOptions.GenericWrapper` for the `Mono<T>` type:

```java
SchemaParserOptions options = SchemaParserOptions.newOptions()
  .genericWrappers(new SchemaParserOptions.GenericWrapper(Mono.class, 0))
  .build();
```

After having passed these options to the `SchemaParser` above, when running a query, I now catch the following exception:

```text
ResolverError: Expected source object to be an instance of 'my.pkg.Article' but instead got 'reactor.core.publisher.MonoCompletionStage'
```

I wanted to try to register a `SchemaParserOptions.GenericWrapper` for `MonoCompletionStage` as well, but [the class is only visible package-wise](https://github.com/reactor/reactor-core/blob/v3.1.2.RELEASE/reactor-core/src/main/java/reactor/core/publisher/MonoCompletionStage.java).

Any idea how I could proceed?

---

Just a naive idea of mine: couldn't inheritance be checked when the `SchemaParserOptions.GenericWrapper`s are used? As `MonoCompletionStage<T>` is a subtype of `Mono<T>`, registering a `SchemaParserOptions.GenericWrapper` for `Mono<T>`*could* then take into account the subtypes of `Mono<T>` somehow... Note that I have no idea of the technical involvements of this ;)

In this case, because [you're already registering a `SchemaParserOptions.GenericWrapper` for `Publisher<T>`](https://github.com/graphql-java/graphql-java-tools/blob/4.3.0/src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt#L273) if I use `.useDefaultGenericWrappers(true)`, I even wouldn't have to register a `SchemaParserOptions.GenericWrapper` for `Mono<T>` as it extends `Publisher<T>`.

---

In the meantime, I'm converting my `Mono<T>` into a `CompletableFuture<T>`:

```java
public CompletableFuture<Article> getArticle(long id) {
  return articleService.findOneById(id).toFuture();
}
```

And then converting the query result back into a `Mono<T>` to make it WebFlux-compliant:

```
Mono.fromFuture(result);
```

**Comment by apottere** [comment]
Makes sense, I can look into checking for a subclass of a generic wrapper.

**Comment by sp00m** [comment]
Little update: I've started playing with `@Batched` fetchers to avoid "select n+1", it would be pretty elegant if I could simply return a `Flux` from these! For example,  say one `Article` is linked to one `Blog`:

```java
public class ArticleResolver implements GraphQLResolver<Article> {
    
  private final BlogService blogService;

  public ArticleResolver(ArticleService articleService) {
    this.articleService = articleService;
  }

  @Batched
  public Flux<Blog> getBlog(List<Article> articles) {
    return blogService.findByArticles(articles);
  }
    
}
```

In the above example, `blogService.findByArticles(articles)` returns a `Flux<Blog>` (pushing as many `Blog`s as inputted `Article`s, plus making sure the inputted `Article`s order matches the the one `Blog`s have been pushed into the `Flux`).

---

A less-but-still elegant API would be to use a `Mono`, e.g.:

```
@Batched
public Mono<List<Blog>> getBlog(List<Article> articles) {
  // ...
}
```

---

What do you think? I'm afraid all this is going kind of out of scope for `graphql-java-tools` though, making it quite tight with [Reactor](https://projectreactor.io/)...

**Comment by sp00m** [comment]
Wait, thinking back to my original issue, there's something I don't really understand: registering a `GenericWrapper` for `Mono` actually successfully validated the schema when creating the `GraphQLSchema` instance. The issue I then faced was at query execution time, because I guess the engine simply doesn't know how to get the actual wrapped value out of the `Mono` (more specifically out of the `MonoCompletionStage`, subtype of `Mono`), which is kind of expected as I haven't registered any kind of _converter_, am I wrong?

If this is true, then what's the use case of actually registering custom `GenericWrapper`s? Because the engine won't ever know how to get the actual value out of it, as it's indeed _custom_... What did I misunderstand here?

**Comment by sp00m** [comment]
Maybe there something to do around [`MethodFieldResolverDataFetcher#get(...)`](https://github.com/graphql-java/graphql-java-tools/blob/master/src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt#L133)?

Because, if I understand correctly, this line basically unwraps an `Optional` (if the returned value is an `Optional`, indeed), which is basically what could be done for a `Mono` (i.e. converting it into a `Future` thanks to `Mono#toFuture()`, as the engine already knows how to handle `Future`s).

So maybe, instead of having this hardcoded only for optional for now, we could think of a way for integrating apps to register custom converters, just like you can currently do for `GenericWrapper`s? Then, this `Optional` conversion could be registered by default, among the possible custom ones.

@apottere, what do you think of all this?
