### ISSUE TITLE
Question, how to get it graphql.servlet.GraphQLContext instance in GraphQLResolver？

### ISSUE THREAD

**Issue by doucheng** [graphql-java/graphql-java-tools#106]
please!

**Comment by apottere** [comment]
Per https://github.com/graphql-java/graphql-java-tools#field-mapping-priority, you can add `DataFetchingEnvironment` as the last argument to any resolve method.  You can then get the context off of that.

**Comment by jacks808** [comment]
example here: https://github.com/graphql-java-kickstart/graphql-java-tools/blob/master/example/src/main/java/com/coxautodev/graphql/tools/example/resolvers/Query.java#L23
