### ISSUE TITLE
Annotated method with List types

### ISSUE THREAD

**Issue by kalthas** [graphql-java/graphql-java-tools#107]
Same error as issue: https://github.com/graphql-java/graphql-java-tools/issues/22

Run into this issue with all latest versions (graphql-java, graphql-java-tools).
The difference is I'm using Google guice.
Reading through that issue post I suppose some 'fixes' were made to spring proxies? And since now I'm using guice proxies it's expected the problem happens again?

**Comment by KammererTob** [comment]
Possibly related: https://github.com/graphql-java/graphql-java-tools/issues/99

**Comment by apottere** [comment]
@kalthas yeah, there hasn't been any work done for guice proxies.  Can you provide a sample project or unit test that shows the failure?

**Comment by kalthas** [comment]
@apottere 
sure. I just created a unit test to reproduce: 
https://github.com/kalthas/graphql-guice

com.aiexpanse.graphqlguice.resolvers.QueryTest#testListInput

and error:
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, com.coxautodev.graphql.tools.SchemaClassScannerError: Unable to match type definition (NonNullType{type=ListType{type=NonNullType{type=TypeName{name='Message'}}}}) with java type (interface java.util.List): Java class is not a List or generic type information was lost: interface java.util.List
  at com.aiexpanse.graphqlguice.SchemaProvider.<init>(SchemaProvider.java:16)
  at com.aiexpanse.graphqlguice.SchemaProvider.class(SchemaProvider.java:16)
  while locating com.aiexpanse.graphqlguice.SchemaProvider
    for field at com.aiexpanse.graphqlguice.guice.GraphQLProvider.provider(GraphQLProvider.java:10)
  at com.aiexpanse.graphqlguice.guice.GraphQLModule.configure(GraphQLModule.java:13)
  while locating com.aiexpanse.graphqlguice.guice.GraphQLProvider
