### ISSUE TITLE
Feature: Schema to Data Class/Resolver Nullability Rules Matches Kotlin Classes

### ISSUE THREAD

**Issue by acidbluebriggs** [graphql-java/graphql-java-tools#11]
It would be a nice feature to have the SchemaParser have the ability to validate that a given type matches the nullability rules in a Kotlin defined data class or resolver.

So, when we have something like this in GraphQL:
```
type Something {
  attributeOne: String!
  attributeTwo: String
}
```
The SchemaParser would fail, and describe the error, if we attempted to define/register a data class for that type if it were defined as the following (note the nullability rules have been flipped in the Kotlin definition):
```
data class Something(attributeOne: String?, attributeTwo: String)
```
Without this option, the only way to find out there is a mismatch between schema and implementation is at runtime. The wonderful thing about Kotlin is that we have that information natively without relying on developers to add annotations and such in Java.
 
We could implement this as an opt-in option in the builder. This would be very easy for Kotlin. There can also be an opt-in for Java classes if they use the @Nullable and @NotNull annotations from Jetbrains. 

Again, I'm willing to implement this. Probably more as a strategy and not inlining it with the current codebase. I'd do the Kotlin one first as that satisfies my immediate needs.

**Comment by apottere** [comment]
I'm planning on adding a bunch of validation of java types -> graphql types (along with some naive discovery), so this sounds like a good candidate for that project.

**Comment by apottere** [comment]
Things along the lines of:
* Verifying that the same class (or subclasses) are used wherever a graphql type appears
* Discovering java types that aren't provided based on return types/parameters

**Comment by apottere** [comment]
For the java case, we can at least verify that `@Nullable` and `@NotNull` are used correctly if they're present by default.

**Comment by acidbluebriggs** [comment]
That's why for the Java case, you'd have to be picky about how to implement the opt-in. Some classes might not have source options (compiled only) so you'd have to be opt-out of the check on specific classes.

**Comment by apottere** [comment]
Yeah, that could get complicated.  I say we start with simple opt-in/opt-out for java and make it more granular if necessary.

**Comment by acidbluebriggs** [comment]
I'd still like to get Kotlin working for me first. :-) As it's what I need/want. So, I'm willing to get going on some sort of first (or last) pass at that. It should be pretty easy actually.

**Comment by apottere** [comment]
Yeah, definitely.  If you want to get started on it, feel free.  I can work it into whatever else I'm doing.

**Comment by acidbluebriggs** [comment]
I've run into some issues with this concept and haven't been able to update anything on it yet. I have edge cases that cause this idea to fail.

**Comment by apottere** [comment]
What are those issues?

**Comment by acidbluebriggs** [comment]
Well, my edge cases are that I am also sometimes proxying to a secondary graphql server. Let's say I have a data class, such as (Kotlin): `Person(name: String, age: Int)`. Then the graphql query searched only for `name`, and that was proxied to the remote server, when the result comes back the `age` value will be null, and the Kotlin class binding will fail (so would Java). Does that make sense? The only thing I can think of doing is then requiring default parameters on all required props (in Kotlin) and having to actually modify, whatever needs to be modified, to apply results by name and not positionally (again, in Kotlin).

**Comment by danielocampo2** [comment]
I think this is a great idea, but I'd be wary of the Java implementation. Happens that there are different @Nullable and @NotNull annotations and none by default in Java sadly. This issue has been faced by Square guys recently and they took a stand on adopting the `javax.annotation` option [https://medium.com/square-corner-blog/rolling-out-nullable-42dd823fbd89](url).
So my suggestion would be to maybe give it a bit more thought to the decision on which one to implement, if we need to choose one.
What are your thoughts on that?

**Comment by cliedeman** [comment]
Hi Guys, I have been looking for exactly the same solution.

@acidbluebriggs I guess you could achieve a similar result using [Optional](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html?is-external=true)?

data class Something(val attributeOne: Optional<String?>, val attributeTwo: Optional<String>)

It feels somewhat clunky but it does represent what actually happens at runtime. I will dig into the code when I have a chance and see if this can work. A starting point would probably be implementing optional for the Java case.

@danielocampo2 It should not be too difficult to accept a customizable list of annotations. This way any custom annotations, even project specific ones, will work.

**Comment by apottere** [comment]
I'm making some pretty major changes to add type discovery that should make this pretty easy to implement.  I think for java it wouldn't be too bad to just find every nullable/nonnull annotation and add a check for it.

It would most likely be a good idea to add a flag to turn off strict validation for use-cases like @acidbluebriggs - maybe a system property?  I don't love using a system property for something like this, but I want to limit how much you actually have to pass to the parser.

**Comment by acidbluebriggs** [comment]
My issue, and why I haven't proceeded with this, is because I didn't think
it through and it fails for my use case. I have some nodes/classes that are
proxies and are forwarded to external graphql servers. So, all my darn
types on those classes have to be optional. When a client requests a subset
of data on the proxied nodes, the binding will fail if a field was defined
as requied yet no value was requested and subsequently not returned. Ugh. I
will eventually figure out a better pattern but for now it's just a bad
idea, for me.

My biggest focus has been on reconstructiong queries and their inputs, and
fragments, based on the sub-node/resolver function they are in so I can
forward that query to an arbitrary path in a remote server. Painful but I
have a messy solution in Kotlin. This solution is going to be in
graphql-Java 3.0, dangit, but I don't have time to wait for that.

What I really hope for is a Kotlin varient of the graphql tools. We can do
much more with named parameters and default values that I can't do with the
Java API.

Sorry for the terse message, on a phone, in a pub.

**Comment by apottere** [comment]
@acidbluebriggs I'd like to see how you'd like a kotlin varient to look.  Yeah, this library isn't really meant to be a graphql endpoint aggregator (I actually want to look at doing something like that in the future).

Now that I'm finished with my changes, this is probably where the field validation should go: https://github.com/graphql-java/graphql-java-tools/blob/master/src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt#L219

That method and `getWrappedClass` unpack fields/return types in order to find more classes and associate them with a graphql type, but it probably wouldn't be too hard to do it at the same time and validate the list/non-null properties of the type are consistent with both graphql and java.

**Comment by apottere** [comment]
I just tried to implement this, and I realized that none of the `@Nullable` or `@NonNull` annotations have runtime retention - this means that it's not actually possible to inspect method return types/parameters for those annotations.  I'll probably add some support for `Optional`, but that's probably as far as it will get.

**Comment by apottere** [comment]
I added some validation around `java.util.Optional` the makes sure it's not being used when the GraphQL type is non-null, but that's the extent of it.

**Comment by acidbluebriggs** [comment]
Yeah, I figure it's not worth it anymore. It really doesn't work for
advanced use cases. :-( You should just close the issue with an "will not
fix" or whatever. I am sorry that I suggested the idea. I've had zero time
to implement anything as I've just been to crazy busy getting this system
to work. I love graphql, if I were the client of it. Implementing the
backend is quite the task when aggregating several microservices, which are
also graphql. I don't recommend that approach.

**Comment by apottere** [comment]
@acidbluebriggs no worries, it was a good discussion to have, and it prompted me to add Optional support which is an improvement.

**Comment by marcust** [comment]
Sorry for commenting on a closed issue, but I have been wondering for a while why this is not done:

1) For the Kotlin case as described in the initial report, I see that apparently @acidbluebriggs has some use cases where it does not work, but the total basic use case that I have a data class that defines something as nullable (`?`) and it is nonnull in the schema (`!`) should be possible, no? Because that leads to an avoidable runtime error and could be checked at startup time.

2) For the Java annotation case, at least the `javax.annotation.Nonnull` has a `RetentionPolicy.RUNTIME` so that should also be an indicator for nullness, so I am not sure which annotations @apottere was looking at. And if you really want it for e.g. Lombok annotations you could use ByteBuddy or similar I guess.
