### ISSUE TITLE
Make output of SchemaClassScanner available programatically

### ISSUE THREAD

**Issue by kclaes** [graphql-java/graphql-java-tools#116]
I'm using code generation to extend a schema with various functionality, which may cause certain types to be generated, only to end up not being used.

The SchemaClassScanner will [issue warnings](https://github.com/graphql-java/graphql-java-tools/blob/master/src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt#L155) for this. 

It would be nice to be able to obtain the list of unused types instead of just getting them in the logs, so I can act upon those warnings.

**Comment by apottere** [comment]
Where would you want that information available?

**Comment by kclaes** [comment]
I'm using the SchemaParser to get a TypeDefinitionRegistry to inspect and put new types in.

If I could somehow just obtain that list of unused types at the end of my process through an invocation of a function, that'd be perfect -- whether that should be on the SchemaClassScanner or some other method on another class, really doesn't matter to me -- I have a feeling you might have a better view on where such functionality should reside in your library?

**Comment by oliemansm** [comment]
I exposed them as `SchemaParser.getUnusedDefinitions()`. Seems to be the easiest way to add this.
