### ISSUE TITLE
Automatically scan for types that implement interfaces

### ISSUE THREAD

**Issue by schmidt-uni-leipzig** [graphql-java/graphql-java-tools#117]
In the following schema, a query is defined that returns a list of an interface. Two concrete types implement hat interface. 

Today, one has to add these types manually to the schema dictionary. Otherwise, one will get a `SchemaClassScannerError`, because the classes for the types are not found (for more information, please see issue #97).

I would like to recomment to scan the schema definition the following way:

1. Find queries that return interfaces (or list of interface instances).
2. Scan for types in the schema that implement that interface even if they are not directly refered in the query definitions.
3. Add these types into the schema dictionary.

```
schema {
    query: Query
}

type Query {
    bases: [Base]
}

interface Base {
    text: String
}

type ChildOne implements Base {
    text: String
}

type ChildTwo implements Base {
    text: String
}
```

**Comment by apottere** [comment]
Unfortunately it's not a good idea to scan for implementations of an interface in java, which is why this library doesn't do it already :/

https://stackoverflow.com/a/3123134

**Comment by apottere** [comment]
That being said I'm definitely open to other ideas about how to discover those children without having to provide them when creating the schema.
