### ISSUE TITLE
BatchedDataFetcher support

### ISSUE THREAD

**Issue by essh** [graphql-java/graphql-java-tools#12]
It would be nice if there was a way for a resolver method to generate a BatchedDataFetcher (details at https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/batched/Batched.java).

Any thoughts on what the API might look like to mark a method as batched?

**Comment by apottere** [comment]
It probably wouldn't be too hard to add support for a `@Batched` annotation on the resolver method.

**Comment by kaqqao** [comment]
Since we're yet to get a DataLoader port in Java, this is IMHO a mandatory feature. Even with the DataLoader, it is still very useful. Without a way to batch the queries, N+1 problem is guaranteed.

**Comment by apottere** [comment]
I'll take a stab at this during my next round of enhancements.

**Comment by sazzer** [comment]
One other option is to support some form of future, so that the resolvers can individually return a future for that piece of data, and they can all be resolved at the end of the query executing.

**Comment by apottere** [comment]
@sazzer returning futures from your resolver methods is already supported, assuming you use an `ExecutionStrategy` that knows how to handle the futures.  Using a multi-threaded `ExecutionStrategy` might have a similar effect.

**Comment by apottere** [comment]
I didn't get to this in my last few updates, but I promise I'm still planning on it :)

**Comment by kaqqao** [comment]
At this point, it might make sense to go for some form of Data Loader support instead...

**Comment by apottere** [comment]
I took a stab at adding support for `@Batched`, not instead of DataLoader but because it seemed easier.  I now understand how to use it and how it would work with this library, but I need to do a little refactoring so I can verify `@Batched` is only used where it's allowed.

**Comment by apottere** [comment]
My understanding so far: `@Batched` is used for resolving individual fields on multiple objects - e.g. if your query returned a list of 10 objects and then requested the `name` field on them, the batched fetcher would get all 10 objects and return a list of 10 names.  Correct me if I'm wrong.

Assuming that's correct, the library could do the following things:

1. For non-root resolver methods, check the method for the `@Batched` annotation.
2. When resolving types for batched methods, require and unwrap a `List` on the return value and *first* parameter.
3. When creating a fetcher, create one that's annotated with `@Batched` that calls the resolver method.

**Comment by kaqqao** [comment]
Yup, your understanding is correct. You get 100 users and request their `name` and the resolver receives all 100 source objects and is expected to return all 100 results (`name`s).

1. Nothing to add :)

2. I think the latest graphql-java relaxed the requirement to an `Iterable` or `Collection`, not sure which though

3.It might be easier to use `BatchedDataFetcher` depending on how your code works (e.g. if you dynamically instantiating it)

**Comment by apottere** [comment]
2. Yeah, I need to do this anyway.  It'll use the same code that I use to unwrap a GraphQLList type, after I verify they're handled the same way.
3. I saw that, but I'm not actually instantiating them dynamically so I can just subclass my data fetcher and annotate it with `@Batched`
