### ISSUE TITLE
Unable to access embedded jpa data repository. Getting 404 not found error while accessing rest api

### ISSUE THREAD

**Issue by sureshpvkumar** [graphql-java/graphql-java-tools#122]
All files are under same package. Also I am able to start the application. But not able to access any URL. Getting 404 error like below.
URL- http://localhost:8080/test
Error :
{
    "timestamp": 1519626747786,
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/test"
}

My POM:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.amex.enterprise.c360</groupId>
	<artifactId>mygraphql</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>mygraphql</name>
	<description>Demo project for Spring Boot</description>

	<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <hbase.version>0.98.12-mapr-1506-m7-4.0.2</hbase.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.10.RELEASE</version>
    </parent>

        <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
       </dependency>

	        <dependency>
	            <groupId>org.json</groupId>
	            <artifactId>json</artifactId>
	            <type>jar</type>
	        </dependency>

			<dependency>
			    <groupId>org.springframework.boot</groupId>
			    <artifactId>spring-boot-starter-data-jpa</artifactId>
			</dependency>
			<dependency>
			    <groupId>org.hibernate</groupId>
			    <artifactId>hibernate-core</artifactId>
			    <version>5.0.9.Final</version>
			</dependency>
			<dependency>
				<groupId>org.hibernate</groupId> 
				<artifactId>hibernate-entitymanager</artifactId> 
				<version>5.2.2.Final</version> 
			</dependency>
			<dependency>
			    <groupId>org.hibernate</groupId>
			    <artifactId>hibernate-validator</artifactId>
			    <version>5.3.6.Final</version>
			</dependency>
			<dependency>
			    <groupId>org.hsqldb</groupId>
			    <artifactId>hsqldb</artifactId>
			    <scope>runtime</scope>
			</dependency>
			<dependency>
			    <groupId>com.graphql-java</groupId>
			    <artifactId>graphql-java</artifactId>
			    <version>6.0</version>
			</dependency>
			
			 <dependency>
			    <groupId>com.graphql-java</groupId>
			    <artifactId>graphql-java-tools</artifactId>
			    <version>3.2.0</version>
			</dependency>

			<dependency>
			    <groupId>com.graphql-java</groupId>
			    <artifactId>graphql-java-servlet</artifactId>
			                       <exclusions>
			                <exclusion>
			                    <groupId>com.fasterxml.jackson.core</groupId>
			                    <artifactId>jackson-databind</artifactId>
			                </exclusion>
			            </exclusions>
			
			    <version>4.7.0</version>
			</dependency>
              <dependency>
                     <groupId>com.graphql-java</groupId>
                     <artifactId>graphiql-spring-boot-starter</artifactId>
                     <version>3.7.0</version>
              </dependency>
              <dependency>
                     <groupId>org.apache.httpcomponents</groupId>
                     <artifactId>httpclient</artifactId>
                     <version>4.5.3</version>
              </dependency>
              <dependency>
                     <groupId>com.jayway.jsonpath</groupId>
                     <artifactId>json-path</artifactId>
              </dependency>
		      <dependency>
		        <groupId>com.google.code.gson</groupId>
		        <artifactId>gson</artifactId>
		        <version>2.7</version>
		      </dependency>
		      <dependency>
		        <groupId>com.googlecode.json-simple</groupId>
		        <artifactId>json-simple</artifactId>
		        <version>1.1.1</version>
		      </dependency>
       </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

My application:

package com.vponn1.graphql;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication
@ComponentScan("mygraphql")
@EnableJpaRepositories("com.vponn1.graphql")
//@EnableAutoConfiguration(exclude={DataSourceAutoConfiguration.class, HibernateJpaAutoConfiguration.class})
public class MygraphqlApplication {

	public static void main(String[] args) {
		SpringApplication.run(MygraphqlApplication.class, args);
	}
}

My Controller:
package com.vponn1.graphql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Profile;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

//import com.vponn1.graphql.GraphqlService;

import graphql.ExecutionResult;

@RestController
//@Profile({"dev","default"})
public class EmployeeController {

    @RequestMapping("/test")
    public String index() {        return "GraphQL Mapping1!!!";    }
    
    @Autowired
    GraphqlService graphqlserv;
	
	@RequestMapping("/graphql")
	@PostMapping
	public ResponseEntity<Object> getAllEmployees (@RequestBody String query){		
		ExecutionResult execute = graphqlserv.getGraphQL().execute(query);
		return new ResponseEntity<>(execute, HttpStatus.OK);
		
	}

	
}

My Model/Bean:

package com.vponn1.graphql;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Table
@Entity
public class Employee {
	@Id
	private String empid;
	private String empname;
	private String dept;
	private String company;
	
	public Employee() {

	}
	
	public Employee(String empid, String empname, String dept, String company) {
		super();
		this.empid = empid;
		this.empname = empname;
		this.dept = dept;
		this.company = company;
	}
	public String getEmpid() {
		return empid;
	}
	public void setEmpid(String empid) {
		this.empid = empid;
	}
	public String getEmpname() {
		return empname;
	}
	public void setEmpname(String empname) {
		this.empname = empname;
	}
	public String getDept() {
		return dept;
	}
	public void setDept(String dept) {
		this.dept = dept;
	}
	public String getCompany() {
		return company;
	}
	public void setCompany(String company) {
		this.company = company;
	}

	

}

My Repository:

package com.vponn1.graphql;

import org.springframework.data.jpa.repository.JpaRepository;

import com.vponn1.graphql.Employee;

public interface EmployeeRepository extends JpaRepository<Employee, String> {
	
	

}

My Service:

package com.vponn1.graphql;

import java.io.File;
import java.io.IOException;
import java.util.stream.Stream;
import javax.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;

import com.vponn1.graphql.AllempdataFetcher;
import com.vponn1.graphql.EmpdataFetcher;
import com.vponn1.graphql.Employee;
import com.vponn1.graphql.EmployeeRepository;

import graphql.GraphQL;
import graphql.schema.GraphQLSchema;
import graphql.schema.idl.RuntimeWiring;
import graphql.schema.idl.SchemaGenerator;
import graphql.schema.idl.SchemaParser;
import graphql.schema.idl.TypeDefinitionRegistry;

@Service

public class GraphqlService {
	

	
	@Autowired
	private AllempdataFetcher allempdataFetcher;
	
	@Autowired
	private EmpdataFetcher empdataFetcher;
	
	@Autowired
	EmployeeRepository emprepo;
	
	@Autowired
	GraphQL graphql;
	
	@Value("classpath:employees.graphql")
	Resource resource;
	
	
	//load schema
	@PostConstruct
	private void loadSchema() throws IOException {
		
		//load Employee initial data
		loadDataIntoHSQL();

		//get schema
		File schemafile = resource.getFile();
		//parse schema and load in registry to keep track of all objects in file
		TypeDefinitionRegistry typereg = new SchemaParser().parse(schemafile);
		//mapping 
		RuntimeWiring wiring = buildRuntimeWiring();
		//make executable schema
		GraphQLSchema schema = new SchemaGenerator().makeExecutableSchema(typereg, wiring);
		//build the schema
		graphql = GraphQL.newGraphQL(schema).build();		

	}
	
	
	private void loadDataIntoHSQL() {
		
		Stream.of( 
				new Employee("A1", "A", "ADEPT", "ACOMP"),
				new Employee("B1", "B", "BDEPT", "BCOMP"),
				new Employee("C1", "C", "CDEPT", "CCOMP")
				)
		.forEach(employee->{
				emprepo.save(employee);
				});

	}

	private RuntimeWiring buildRuntimeWiring() {

		return RuntimeWiring.newRuntimeWiring()
				.type("Query", typeWiring -> typeWiring
								.dataFetcher("allEmployees", allempdataFetcher)
								.dataFetcher("employee", empdataFetcher))
				.build();
	}
	
	public GraphQL getGraphQL() {
		return graphql;
	}

}

My Datafetchers:

package com.vponn1.graphql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.vponn1.graphql.Employee;
import com.vponn1.graphql.EmployeeRepository;

import graphql.schema.DataFetcher;
import graphql.schema.DataFetchingEnvironment;

@Component
public class EmpdataFetcher implements DataFetcher<Employee> {
	
	@Autowired
	EmployeeRepository emprepo;

	@Override
	public Employee get(DataFetchingEnvironment dataFetchingEnvironment) {
		String empid = dataFetchingEnvironment.getArgument("id");
		return emprepo.findOne(empid);
	}

}

package com.vponn1.graphql;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.vponn1.graphql.Employee;
import com.vponn1.graphql.EmployeeRepository;

import graphql.schema.DataFetcher;
import graphql.schema.DataFetchingEnvironment;

@Component
public class AllempdataFetcher implements DataFetcher<List<Employee>> {

	@Autowired
	EmployeeRepository emprepo;
	
	@Override
	public List<Employee> get(DataFetchingEnvironment dataFetchingEnvironment) {
		return emprepo.findAll();
	}

}

My Query file:

schema {
	query: Query
}

type Query {
	allEmployees : [Employee]
	employee(id:String) : Employee
}

type Employee {
	empid : String
	empname: String
	dept : String
	company : String
}

**Comment by geesen** [comment]
First: please use a proper code-styling - it's hard to read... 

I think this is a Spring Boot issue, because you set the component scanning to 
`@componentscan("mygraphql")`
so that Spring Boot will only scan these package for components. 
Your controller component (`@RestController`) is in this package:
`package com.vponn1.graphql;`

Thus, your controller is never picked up by Spring Boot, which in turn never creates the request mapping for `/test/` - so it does not exist and you'll get a 404.

**Comment by apottere** [comment]
Your code doesn't seem to even use this project, despite including it as a dependency.  The "runtime wiring" support is native to graphql-java.
