### ISSUE TITLE
DataFetcherResult support for data + errors

### ISSUE THREAD

**Issue by elenigen** [graphql-java/graphql-java-tools#124]
In graphql-java v7.0, the DataFetcherResult class has been introduced to follow the [GraphQL specification:](http://facebook.github.io/graphql/October2016/#sec-Errors)
> If the data entry in the response is not null, the errors entry in the response may contain any errors that occurred during execution. If errors occurred during execution, it should contain those errors.

Unfortunately, when I try to use it with graphql-java-tools 4.3.0, the feature won't work, because the schema parser tries to map the Java types with the defined schema types and it would complain about `DataFetcherResult`, since it's not a defined type:
`public DataFetcherResult<Iterable<User>> createUsers(List<User>)`

It would fail with this error:
```
... Constructor threw exception; nested exception is com.coxautodev.graphql.tools.SchemaClassScannerError: Unable to match type definition (ListType{type=TypeName{name='User'}}) with java type (graphql.execution.DataFetcherResult<java.lang.Iterable<com.test.User>>): Java class is not a List or generic type information was lost: graphql.execution.DataFetcherResult<java.lang.Iterable<com.test.User>>
```
Is this feature would be available in a coming version?  I saw the master branch is no longer compatible with graphql-java v7.0, so I guess the first part would be to fix this ...
From what I understand the change would be very trivial, we just need to invoke `getData()` on a `DataFetcherReult` before calling `typeClassMatcher.match`.

**Comment by maarek** [comment]
Once v8.0 merges in, can we get a PR in for this?

**Comment by apottere** [comment]
Just a note on this, it looks like this feature isn't supported by `BatchedExecutionStrategy` since that execution strategy is deprecated, so you can't have both at once.
