### ISSUE TITLE
Allow multiple GraphQLResolvers for one same DataClass

### ISSUE THREAD

**Issue by sp00m** [graphql-java/graphql-java-tools#125]
For clean code purposes, I'm trying to have multiple `GraphQLResolver` for one same DataClass, e.g.:

```java
public class ArticleBlogResolver implements GraphQLResolver<Article> {

  public Blog getBlog(Article article) {
    return ...;
  }

}

public class ArticleCommentsResolver implements GraphQLResolver<Article> {

  public Collection<Comment> getComments(Article article) {
    return ...;
  }

}
```

Unfortunately, this is not yet possible: the schema validation fails because `getComments` cannot be found on `ArticleBlogResolver`.

What do you think?

**Comment by black237** [comment]
I tracked down the problem to `SchemaClassScanner.scanQueueItemForPotentialMatches()`. From there the `resolverInfosByDataClass` field is used to get the related type resolver(s). The field `resolverInfosByDataClass` is set by using `this.resolverInfos.associateBy { it.dataClassType }`. The  `associateBy { ... }` method is clearly saying this: "_If any two elements would have the same key returned by [keySelector] the last one gets added to the map._"

In my case I can see that the collection `resolverInfos` contains all the type resolvers of interest. But by using `associateBy { ... }` the number of resolvers is striped down to 1. From my perspective this "filter" is not working properly.

**Comment by taxidriver61** [comment]
[#136](https://github.com/graphql-java/graphql-java-tools/pull/136)

**Comment by apottere** [comment]
#136 merged
