### ISSUE TITLE
Schema file comments

### ISSUE THREAD

**Issue by alkismavridis** [graphql-java/graphql-java-tools#126]
I use schema files extensively, and I really enjoy the easiness of writing # comments ,
and see those in graphiql UI as extra documentation for my clients.

But I would also like to be able to write comments like todos, suggestions for my team, or even special comments for my IDE (like region/endregion in intellij).

**So the question is:**
can I somehow write comments that will not be visible via __schema  queries?

Thanks a lot!

**Comment by apottere** [comment]
Do you have an idea of how you would want it to work?  Right now any comments are parsed by the `graphql-java` parser and copied verbatim to the description.  There would have to be some sort of convention on top of that so we could filter out "internal" comments (e.g. `##` or `#-` etc).

**Comment by alkismavridis** [comment]
Hello @apottere ! Thanks for you reply.
I can imagine 2 ways of doing that:

1. As you mentioned, find a "magic" start that would filter out the comment, like ##
2. Let the user specify this "magic" comment start by the user using a string, or (even better) a callback:
`GraphQL
                .newGraphQL(schema)
                .setCommentFilter(str -> !str.startsWith("##"))   //only comments that satisfy the condition will be included
                .build();`

**Comment by alkismavridis** [comment]
Hello @apottere 
I see that the issue is closed.
What have you finally decided?

Best regards.
Alkis Mavridis
