### ISSUE TITLE
Combine data and resolvers?

### ISSUE THREAD

**Issue by alamothe** [graphql-java/graphql-java-tools#132]
I'm wondering why "data" and "resolver" classes are separated. What are pros and cons of having just a single class? 

As an example, instead of:
```java
class Book {
    private int id;
    private String name;
    private int authorId;
    
    // constructor
    
    // getId
    // getName
    // getAuthorId
}

class BookResolver implements GraphQLResolver<Book> /* This class is a resolver for the Book "Data Class" */ {
    
    private AuthorRepository authorRepository;
    
    public BookResolver(AuthorRepository authorRepository) {
        this.authorRepository = authorRepository;
    }
    
    public Author author(Book book) {
        return authorRepository.findById(book.getAuthorId());
    }
}
```

Have a:
```java
class Book {
    private int id;
    private String name;
    private int authorId;
    
    // constructor
    
    // getId
    // getName
    // getAuthorId

    public Author author() {...}
}
```
(note a reference to `Book` is no longer necessary)

**Comment by alkismavridis** [comment]
We use extensively the separation between the resolver and the entity in our application. The most significant benefit that we gain is architecture. We can use graphQL this way, no matter what our architecture is.

For us it works like this:
The core of our application are services, not entities.
Services refere to our entities, and never the other way around.
Entity objects are simple state wrappers.

Entities do not store all field that API needs to offer.
As an example, we support messages/notifications for a user. But those are not stored in the user entity itself, but in a separate NotificationService, which works on its own way.

Also, Services can talk to each other and consistently synchronize their actions.
Our application was working like that before we start using graphQL, and we want to keep it this way.

With resolvers, we **can** keep it this way.
Resolver is just a middle man, has access to all our services and can give information that the entity itself cannot provide, and in our oppinion, it should not provide.

But as mentioned, this is how we built our architecture. Different people want different architectures.
Resolvers give us the flexibility to keep our entities plain and simple, and move this complexity somewhere else.

**Comment by apottere** [comment]
Thanks for the great response @alkismavridis.  Like they said, applications are often architected in such a way that entity classes don't have all the information necessary to resolve the links to other entities - resolvers fill that gap.  In our experience, we were using data classes generated by gRPC, so we didn't have the ability to add custom methods wherever we wanted them.

That being said, you don't *have* to use resolvers - you can add any methods you want to the data class and call it a day.
