### ISSUE TITLE
Allow overriding standard scalars

### ISSUE THREAD

**Issue by Yogu** [graphql-java/graphql-java-tools#133]
Currently, standard scalars can not be overriden as custom scalars with the name of a standard scalar are [filtered out](https://github.com/graphql-java/graphql-java-tools/blob/master/src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt#L143). It would however be useful to e.g. provide a custom `ID` type that uses a different underlying type (like `UUID`) and provides appropiate serializers and deserializers.

The reason for not using a custom name like `UUID` is that relay assumes the `id` field's type is `ID`.

**Comment by vojtapol** [comment]
This would be really helpful for us. We would like to trim and clean up all input strings in one place and I think it would be easy by tweaking the `GraphQLString` scalar parser.

**Comment by vojtapol** [comment]
Trying to override Scalar type now fails when `graphql-java` checks the schema in `SchemaUtil:87` with message:
```
No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).
You have redefined the type 'String' from being a 'GraphQLScalarType' to a 'GraphQLScalarType'
```

Maybe we should revert this issue then?
