### ISSUE TITLE
Partial update in resolver

### ISSUE THREAD

**Issue by KrifaYounes** [graphql-java/graphql-java-tools#141]
it's possible to do partial update in the resolver ?
i have a input to update with only field specified by user like this blog
thanks
https://medium.com/workflowgen/graphql-mutations-partial-updates-implementation-bff586bda989

**Comment by oliemansm** [comment]
I read the article, but this feature relies on the Javascript feature that a variable can be `undefined` or `null`. Java doesn't have an equivalent of `undefined`. That would mean that `null` values would be automatically passed in for parameters that aren't provided in the mutation. How would you know when you would actually have to set them to `null` and when would you have to ignore them and leave the value as is? Long story short: partial updates are not supported.

**Comment by KrifaYounes** [comment]
@oliemansm  it's possible 
show my code : 
https://github.com/KrifaYounes/spring-boot-graphql/blob/master/src/main/java/com/example/demo/graphql/mutation/AuthorMutationResolver.java

**Comment by AllirionX** [comment]
I am late to the party but it is possible to implement an Undefined<T> class, inspired from Optional<T> to deal with this use case (code improved from @KrifaYounes idea):
```
public final class Undefined<T> {

  private static Undefined<?> UNDEFINED = new Undefined();
  private boolean defined;
  private T value;

  private Undefined() {
    this.defined = false;
    this.value = null;
  }

  public static <T> Undefined<T> getInstance() {
    @SuppressWarnings("unchecked")
    Undefined<T> t = (Undefined<T>) UNDEFINED;
    return t;
  }

  public Undefined(T value) {
    this.defined = true;
    this.value = value;
  }

  public boolean isDefined() {
    return defined;
  }

  public T getValue() {
    return value;
  }
}
```

The schema:
```
input BookInput {
  title: String
}
```

The input:
```
public class BookInput {
  Undefined<String> title = Undefined.getInstance();

  public Undefined<String> getTitle() {
    return this.title;
  } 
  public void setTitle(String title) {
    this.title=new Undefined(title);
  }
}
```

In the resolver use:
```
if(input.getTitle().isTitle()) {
  book.setTitle(input.getTitle().getValue();
}
```
  
This approach removes the needs to perform several contains operations and to have the literal key hard-coded.
I also use this with spring validation: I can annotate the undefined input field with a custom annotation that can use the undefined state to perform the validation.

**Comment by DirkLachowski** [comment]
@AllirionX 
Shouldn't the resolver part be:

```java
if(input.getTitle().isDefined()) {
  book.setTitle(input.getTitle().getValue();
}
```

**Comment by AllirionX** [comment]
Indeed it should be! I updated the code snippet.

**Comment by alexsaleh** [comment]
A bit late here. @AllirionX great solution! I'm struggling to get it to work however. Jackson does not seem to play well with generics and I'm getting the following error:
`Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `Undefined` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value`

How did you solve this issue?

**Comment by kliakos** [comment]
> I am late to the party but it is possible to implement an Undefined class, inspired from Optional to deal with this use case 

Why not use `Optional<T>` directly? Null field value to indicate the undefined and `Option.empty()`  to indicate the explicit null.
