### ISSUE TITLE
Upgrade to graphql-java 9.0

### ISSUE THREAD

**Issue by utwyko** [graphql-java/graphql-java-tools#144]
`graphql-java` version 9.0 has been released. It would be great if `graphql-java-tools` could be updated to use this new version.

I tried to do the upgrade in my fork, and after an adjustment to how the `DataFetchingEnvironmentImpl` was instantiated in tests, got all tests passing.

However, when I try to use the new version in an actual application, no queries seems to be resolved, I'm only getting timeouts. 

I will try to publish a project that reproduces this issue later on.

**Comment by vojtapol** [comment]
I tried `graphql-java` 9.0 and for the most part everything worked fine.

However, mutations that return type which has fields resolved by a data-loader get stuck on:
`GraphQL.class:150`
```
return (ExecutionResult)this.executeAsync(executionInput).join();
```

It could be related to https://github.com/graphql-java/graphql-java/pull/990 but that is also very much the reason I need `graphql-java` 9.0.0

If I exclude the data-loader fields from the query, the mutation work fine. Also, it never happens for queries, only for mutations.

**Comment by aviadavretz** [comment]
Any news about this?
would love to use graphql-java 9.2 with this library :)

**Comment by yarinvak** [comment]
Is there any progress? I would like to use schema directives in my project

Thanks!
