### ISSUE TITLE
Customzied context-path will break GraphiQL

### ISSUE THREAD

**Issue by pclnzwang** [graphql-java/graphql-java-tools#147]
I upgrade the version of spring boot parent to 2.0.1.RELEASE in the example project.

After customizing the server.servlet.context-path=/a/, grahiql stops loading shcema.
remove the changes of server.servlet.context-path will be fine.

Fox example
http://localhost:8090/a/graphiql

**Comment by pclnzwang** [comment]
Just figure it out.

Use server.servlet.path instead.

**Comment by ezinzombe** [comment]
Yes Thanks adding 
server.servlet.path=/demo for example works
