### ISSUE TITLE
Update reflectasm to 1.11.7

### ISSUE THREAD

**Issue by asfernandes** [graphql-java/graphql-java-tools#152]
reflectasm 1.11.3 has a dependency to an older version of asm, that conflicts with spring-boot 2.0.3.

**Comment by asfernandes** [comment]
Will a new version of graphql-java-tools be available soon?

**Comment by apottere** [comment]
It should be going out sometime today, as soon as I can get graphql-spring-boot released.

**Comment by apottere** [comment]
All at the mercy of sonatype syncing.

**Comment by apottere** [comment]
Aaaand its actually released in `5.2.3` because the deploy process broke.

**Comment by asfernandes** [comment]
Did you already published to maven central or another repository?

I still didn't see it in central.

**Comment by apottere** [comment]
I just verified it did sync to oss.sonatype.org, so it should have showed up in maven central search a few hours after that - if it doesn't show up by tomorrow I'll try releasing it again.  Sometimes sonatype can be painfully slow :(

**Comment by apottere** [comment]
I tried republishing it to maven central, hopefully it'll work this time.  Should show up here in a few hours if it worked: https://repo1.maven.org/maven2/com/graphql-java/graphql-java-tools

**Comment by apottere** [comment]
I submitted this issue, so hopefully it gets fixed soon: https://issues.sonatype.org/browse/OSSRH-41506
