### ISSUE TITLE
How can i use constraint validations?

### ISSUE THREAD

**Issue by mpbalmeida** [graphql-java/graphql-java-tools#153]
I just started using graphql and spring boot.

I have implemented the simple Author - Book example using JPA and it works fine, my doubt is if I Create an email field, how can i validate if it is an e-mail using `@Email` from `javax.validation.constraints` ?

My class would be something like this

```@Data
@Entity
public class Author {
    @Id
    @GeneratedValue
    private Long id;
    private String name;
    @Email
    private String email;
}
```

**Comment by oliemansm** [comment]
As you've probably noticed GraphQL doesn't perform these validations automatically. Thus you would have to execute them yourself manually. The example you provide is a JPA entity though, and to make sense for GraphQL I would expect it to be on an input object for example. Looks like you're mixing concerns here.

Take a look at this article for a detailed description on how to validate manually: https://www.baeldung.com/javax-validation.
