### ISSUE TITLE
Is EndToEndSpec.kt executed during build process?

### ISSUE THREAD

**Issue by gipeshka** [graphql-java/graphql-java-tools#154]
Hey guys!

I've just tried to break the specification locally, unfortunately maven is still reporting build success.

Looking into the specification itself I didn't find a test class in, rather a script. So the question is whether there's a special way to execute this specification or is it simply ignored?

**Comment by oliemansm** [comment]
Looks like `EndToEndSpec.groovy` calls `EndToEndSpecKt.createSchema()` to create the schema as defined in the Kotlin file. So it looks like the Kotlin file is used to define the actual test schema with the types and resolver classes which is uses by the Groovy test specifiction.
