### ISSUE TITLE
GraphQL is not getting exposed on a different endpoint

### ISSUE THREAD

**Issue by sharmmoh1983** [graphql-java/graphql-java-tools#159]
I have tried using

graphql:
      servlet:
               mapping: /test
               enabled: true
               corsEnabled: true

GraphQL is not getting exposed on a different endpoint
I did not see any which way where /graphql van be exposed to some other point
Also /graphql is giving 400 bad request, it is only expecting query parameters

Only /graphiql is working which is a html page

How can we expose /graphql or any user defined url  as as endpoint with post body?

**Comment by oliemansm** [comment]
Wrong project again, you need to create the issue over here: https://github.com/graphql-java/graphql-spring-boot
