### ISSUE TITLE
How can I tell which fields are requested?

### ISSUE THREAD

**Issue by casramsey** [graphql-java/graphql-java-tools#16]
I'm new to this, but managed to get up and running no probs - looks great.  

I'm not sure if I'm missing something though - how am I able to know which fields have been requested?  My back end is an oracle DB with potentially hundreds of different columns coming back.  If the client only asks for 3, I only want to query the DB with 3 - is there an object that will give me the columns (fields) that the client has requested?

Thanks
Jason

**Comment by apottere** [comment]
If you add an extra argument to your resolver method, you can inject the `DataFetchingEnvironment` which should give you access to the requested fields

**Comment by casramsey** [comment]
@apottere 
Boom!  Couldn't find this anywhere!  Thanks man!
