### ISSUE TITLE
Returning data and errors

### ISSUE THREAD

**Issue by pclnzwang** [graphql-java/graphql-java-tools#161]
Our app is heavily working with graphql-java-tools now and we need to return the data and errors in the response at the same time after we catch some checked exception during the fetching data process.

{
"data": {xxx}
"errors": [{error1, error2}]
}

I did some research and found out some example below by override DataFetcher(). 

http://graphql-java.readthedocs.io/en/latest/execution.html#exceptions-while-fetching-data
http://graphql-java.readthedocs.io/en/latest/execution.html#returning-data-and-errors

Anyone knows how we can do this with graphql-java-tools as we don't use DataFetcher?

**Comment by zhewang2** [comment]
I figured out by wrapping up data and errors in DataFetcherResult inside resolver function.

    fun methodName( parameter: String ): DataFetcherResult<List<Data>> {
        val data = mapper.map(  parameter  )
        return DataFetcherResult( data.data, data.errors )
    }

**Comment by pclnzwang** [comment]
I figured out by wrapping up data and errors in DataFetcherResult inside resolver function.

fun methodName( parameter: String ): DataFetcherResult<List<Data>> {
    val data = mapper.map(  parameter  )
    return DataFetcherResult( data.data, data.errors )
}
