### ISSUE TITLE
Unable to determine data class for resolver '...' from generic interface!  This is most likely a bug with graphql-java-tools.

### ISSUE THREAD

**Issue by CH-EricLundberg** [graphql-java/graphql-java-tools#163]
I started getting that error today when trying to make a set of resolvers more generic.  I.e., a `public abstract class FooQueryResolver<T extends Foo> implements GraphQLResolver<T> {
   public String getValue (T foo) { return foo.getValue();}
}` and then other resolvers for the child classes like `BarResolver extends FooResolver<Bar>` (where Bar is a child class of Foo) 

I've tried playing around making the actual Foo example with two simple subclasses and it seems to work so I'm guessing it is how I have my actual real resolvers setup, but my real example is more complicated so maybe it is a bug.  

Any thoughts on how to work out if this is a graphql-java-tools bug or an error with how I have my resolvers set up?

**Comment by CH-EricLundberg** [comment]
Looks like it is a bug (or more likely: not yet implemented) In my Foo example that was 'working' I was using abstract resolvers and only looking at the polymorphism in the objects.  When I made concrete resolvers to change the shape of the schema leaving the objects along I got the same issue.  

It would be handy to have as I think people implementing graphql on top of existing code do not always have the luxury of making POJOs to match the desired schema.  And there is an argument to be made that the shape of the objects used for the graphql view may not / should not always be the same as the same used for OO modeling (which may not make the db modeling, etc)

Seems like it would be relatively straightforward to support since the concrete resolvers have an exact class reference, but I don't know any kotlin to try to shoehorn that in there.  Can any of the active developers comment on the likely hood of this being supported?

To work around the issue is straight forward in that you can replicate the code that would be in the abstract base resolver and push it into multiple concrete resolvers, but it is duplicated code (even when simple wrapper functions) which is a little uggo.

**Comment by oliemansm** [comment]
So basically when you have these classes set up:
```java
public abstract class FooQueryResolver<T extends Foo> implements GraphQLResolver<T> {
  public String getValue(T foo) {
    return foo.getValue();
  }
}

public class BarResolver extends FooResolver<Bar> {

}
```
And you have a schema like:
```
type Bar {
  value: String!
}
```
It can't find it, because the reflection apparently doesn't look at superclasses?

**Comment by CH-EricLundberg** [comment]
That seems to be it exactly.  I have made BarResolver (and other children) have their own getValue call which can call the super class which has the complete implementation, so they are just 'one liner' methods, but still not great from a class design point of view.

**Comment by CH-EricLundberg** [comment]
@karl-run if you are up to it you could code review the PR I wrote to add an option for preferring the resolvers. ;)

**Comment by oliemansm** [comment]
Added a fix for this. In the example above the `BarResolver` is the one that needs to implement `GraphQLResolver` though, since the scanner searches for implementors of that interface as resolvers. So the example would become:
```java
abstract class FooResolver<T> {
    String getValue(T foo) {
        return "value"
    }
}

class BarResolver extends FooResolver<Bar> implements GraphQLResolver<Bar> {

}
```
See also `GenericResolverSpec.groovy` for a test showing usage.

**Comment by oliemansm** [comment]
Confirmed through a test that the below setup works as well:
```java
abstract class FooResolver<T> implements GraphQLResolver<Bar> {
    String getValue(T foo) {
        return "value"
    }
}

class BarResolver extends FooResolver<Bar> {

}
```

**Comment by mxmlnglt** [comment]
> Confirmed through a test that the below setup works as well:
> 
> ```java
> abstract class FooResolver<T> implements GraphQLResolver<Bar> {
>     String getValue(T foo) {
>         return "value"
>     }
> }
> 
> class BarResolver extends FooResolver<Bar> {
> 
> }
> ```

Same here; @oliemansm: are you sure you didn't actually mean `abstract class FooResolver<T> implements GraphQLResolver<T>`?
