### ISSUE TITLE
Can expose a interface to support invoke custom annotation on method in resolvers

### ISSUE THREAD

**Issue by mjd507** [graphql-java/graphql-java-tools#172]
Background: some service in my project need user authorization, some not, and I handle in the custom `GraphQLContextBuilder` and override the `build` method, return a custom AuthContext that may contain a user or not.  then every method in resolver that need user, I should write the same check user method, some code like below:

`build` method in custom `GraphQLContextBuilder`
```java
    @Override
    public GraphQLContext build(HttpServletRequest request) {
        User user = Optional.of(request)
            .map(req -> req.getHeader("Authorization"))
            .map(token -> {
                // 1. find userId by token
                String userId = redisUtils.get("xxx:token:" + token);
                // 2. find user by userId
                return Optional.ofNullable(userId)
                    .map(Long::valueOf)
                    .map(id->userService.getUser(id))
                    .orElse(null);
            }).orElse(null);

        return new AuthContext(user, request);
    }
```
AuthContext.java
```java
public class AuthContext extends GraphQLContext {

    private final User user;

    AuthContext(User user, HttpServletRequest request) {
        super(request);
        this.user = user;
    }

    public static User checkUser(DataFetchingEnvironment context) {
        AuthContext authContext = context.getContext();
        User user = authContext.getUser();
        if (user == null) {
            throw new UnauthorizedException();
        }
        return user;
    }

    public User getUser() {
        return user;
    }
}
```
updateUserInfo method in `UserResolver` that implements `GraphQLMutationResolver`
```java
    public User updateUserInfo(User newUser, DataFetchingEnvironment context) {
        User oldUser = AuthContext.checkUser(context);
        User needUpdateUser = CopyUtils.copyObjectIgnoreNull(newUser, oldUser);
        return userService.updateUser(needUpdateUser);
    }
```

------
I want to define a annotation for example `@NeedAuth`  to make the authorization simple, and if the method do not need authorization just do this:
```java
    @NeedAuth(value = false)
    public User login(String name, String pwd) {
        User user = userService.login(name, pwd);
        return user;
    }
```
and if the value is true (default), then I wish I can get the user in the last param.

------
I find that method in resolvers are invoked by the code in the `MethodFieldResolver.kt`
```kotlin
    override fun get(environment: DataFetchingEnvironment): Any? {
        val source = sourceResolver(environment)
        val args = this.args.map { it(environment) }.toTypedArray()
        val result = methodAccess.invoke(source, methodIndex, *args)
       ...
    }
```
so can expose a interface here that to invoke my custom annotation before invoke the real method and receive my return value to the last param ?

or any better ways to handle authorization and user ? (not invoke in every need method)

**Comment by oliemansm** [comment]
I tend to put these security concerns in a different layer. Not in the GraphQL layer itself, but in the application layer. Because GraphQL is just one of the interfaces that might be accessing/modifying the data in my app, and every other interface will need to use the same kind of security. If you bind your security this way with the GraphQL solution, you're making it harder for yourself to ever make any changes to it in the future. So I would advice against it actually.

Since my projects usually are Spring based I use Spring Security for that. You don't use any existing frameworks like that to help you?

**Comment by mjd507** [comment]
ok, you're right, since I know very little about Spring Security, I don't use it in my project. and  it's  time for me to learn it . thank you!

**Comment by pedroviniv** [comment]
although agree with @oliemansm about the security stuff. I think it would be nice if we could "intercept" the method resolver calls to customize the params passed to the method. Is there any way to do that?
