### ISSUE TITLE
SchemaParser

### ISSUE THREAD

**Issue by sra-013** [graphql-java/graphql-java-tools#176]
I am unable to pass a .graphqls file to the parse function of SchemaParser. How to do it?

**Comment by oliemansm** [comment]
You have to read the file into a `String` first and use that together with the `SchemaParserBuilder`.

```java
String schemaString = readSchemaFile("file.graphqls"); // this is your own method to read the file
SchemaParserBuilder builder = new SchemaParserBuilder();
builder.schemaString(schemaString);
SchemaParser parser = builder.build();
```

This snippet doesn't show the use of dictionary or resolvers btw, but only focuses on reading a schema file.

**Comment by sra-013** [comment]
Worked. Thanks. :)

**Comment by oliemansm** [comment]
btw, just saw in a unit test that you can do it even simpler:
```java
SchemaParser.newParser().file("file.graphqls").build();
```
