### ISSUE TITLE
Performance Issue with hundred fields in the Query

### ISSUE THREAD

**Issue by pclnzwang** [graphql-java/graphql-java-tools#177]
I was building application based on tutorial below and find a performance issue that the execution time will be 100 times slower (50 ms - 5000 ms) after I  add 100 fields into the query. 

Anyone has any experience how to improve it?

https://www.pluralsight.com/guides/building-a-graphql-server-with-spring-boot

**Comment by ccamel** [comment]
What kind of graphql query are you doing? Can you provide an example?

As part of the tutorial, you may experience performance issues because of the join between the `Book` and `Author` entities (common issue known as [N+1 issue](https://engineering.shopify.com/blogs/engineering/solving-the-n-1-problem-for-graphql-through-batching)), like in this query:

```graphql
{
  findAllBooks {
    id
    isbn
    title
    pageCount
    author {
      firstName
      lastName
    }
  }
}
```

**Comment by pclnzwang** [comment]
@ccamel  Thank you for replying.

The issue I am facing right now is that fetching hundred of fields within hundred of offers has significant delay.

Log:
[09-06-18 11:13:34.904] [https-jsse-nio-8443-exec-4] DEBUG  g.execution.ExecutionStrategy - 'cfaf6f40-323e-4479-bc22-f15323add557' fetching field '/offersByToken[98]/products/air/slices[0]/segments[1]/destination/countryName' using data fetcher 'com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher'...

schema looks like below:

`{
email
offer {
  offerId
  ...100 fields
}
}`

**Comment by pclnzwang** [comment]
actually we have 200 fields in the schema and resolver will return 100+ offers back.

That is 200 * 100 (20000) fields fetching job and it will take at least 1000 ms to process...

**Comment by pclnzwang** [comment]
Set the logging level as INFO instead of DEBUG.
