### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by jamsheer-thottathil** [graphql-java/graphql-java-tools#18]
How to implement  pagination, Is there any way is already available ?

**Comment by apottere** [comment]
GraphQL doesn't have pagination built-in.  You can implement it yourself or you can use a pattern like https://facebook.github.io/relay/

If you're implementing it yourself, just add a cursor argument and use that to determine what info to look up.

**Comment by jamsheer-thottathil** [comment]
Thank you for your  reply
