### ISSUE TITLE
Protected resolver methods are not detected anymore (v5.2.4)

### ISSUE THREAD

**Issue by oorakci** [graphql-java/graphql-java-tools#182]
Hi,

PR #167 breaks protected methods in resolvers in v5.2.4, because "type.methods.toList()" returns only public methods.

https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getMethods()

**Comment by oliemansm** [comment]
Right, so `(type.methods.toList() + ClassUtils.getAllSuperclasses(type).flatMap { it.methods.toList() })` should probably simply be reverted to `(type.declaredMethods.toList() + ClassUtils.getAllSuperclasses(type).flatMap { it.methods.toList() })` to fix this.
