### ISSUE TITLE
SchemaClassScannerError when using float and  java.lang.Float

### ISSUE THREAD

**Issue by mark-james** [graphql-java/graphql-java-tools#19]
I'm getting a runtime error with 3.0.1 because my data classes are using a mixture of java.lang.Float and float. 

com.coxautodev.graphql.tools.SchemaClassScannerError: Two different classes used for type Float:

Is there a way of overriding this behaviour. As I'm not able to change the classes. I've worked around it by creating wrappers in the resolver class to make everything consistent. But that seems like quite a bit of redundant effort. 

Thanks
Mark

**Comment by apottere** [comment]
Yeah, this is definitely a bug - the library should be smart enough to box primitives.  I'll push out a fix asap.

**Comment by apottere** [comment]
This is released in 3.0.2.
