### ISSUE TITLE
Graphql java tools cannot resolve type classes properly

### ISSUE THREAD

**Issue by oexza** [graphql-java/graphql-java-tools#20]
Kindly take a look at this project https://github.com/oexza/graphql-java-tools-reactive-test it throws
`Constructor threw exception; nested exception is java.lang.IllegalArgumentException: value already present: class java.lang.String
`
it appears some funky stuff is going on with the type resolution. It may help to know that it works with version 2.3.0 of graphql-java-tools(without returning CompletetableFuture from the resolver). thanks

**Comment by apottere** [comment]
I took a look at the sample project, and it looks like this is because I overlooked that custom scalars can have the same java type as primitives.  I'll work on a fix tomorrow morning.

Thanks for the great bug reports!

**Comment by apottere** [comment]
@oexza this is released in `3.1.0`

**Comment by oexza** [comment]
Nice. i shall test it out later today

**Comment by oexza** [comment]
Problem still persists except its with the Node interface this time. I've updated the project, please take a look. thanks.

**Comment by oexza** [comment]
ping!!!

**Comment by apottere** [comment]
Sorry, I had a busy and of the week.  I'll take a look first thing monday.

**Comment by apottere** [comment]
I tested the sample project with 3.1.2 and it starts, let me know if you find any other issues though.

**Comment by oexza** [comment]
Thanks. I will try it out when it shows up on maven central.
