### ISSUE TITLE
Override Internal Server Errors

### ISSUE THREAD

**Issue by donbeave** [graphql-java/graphql-java-tools#23]
Hello, guys!

First of all thank you for this awesome library.

But I have a question, some of my methods in `GraphQLQueryResolver` throws exceptions, like `AccessDeniedException`, `UnauthorizedException`, ...

Result for `/graphql` will be something like:

```json
{
  "data": {
    "roles": null
  },
  "errors": [
    {
      "message": "Internal Server Error(s) while executing query"
    }
  ]
}
```

How can I override this behaviour for some of my exceptions and do custom error response?

Something like:

```json
  "errors": [
    {
      "errorCode": "ACCESS_DENIED",
      "message": "You don't have permission to access roles"
    }
  ]
```

**Comment by apottere** [comment]
It looks like you're using graphql-java-servlet, which is hiding the error.  You can extend the servlet and override the method that filters exceptions to allow more to be shown to the client.

**Comment by apottere** [comment]
If you have any more questions, would you mind opening an issue on that project instead?

**Comment by balaramkolluru** [comment]
Could not save owner: Error: GraphQL error: Internal Server Error(s) while executing query

**Comment by balaramkolluru** [comment]
im using postgresql db for my application im getting this error , any one please help

**Comment by balaramkolluru** [comment]
with frontend part, im listing all owners but cant update it.
