### ISSUE TITLE
kotlinx coroutines CompletableFuture 

### ISSUE THREAD

**Issue by tristancaron** [graphql-java/graphql-java-tools#27]
Writing a resolver using `kotlinx-coroutines-jdk8`

```kotlin
fun allUsers() = future {
  arrayListOf()
}
```
Throws an error,  `CompletableFutureCoroutine cannot be cast to java.lang.Iterable`

It does the same when using CompletableFuture without kotlinx

**Comment by oexza** [comment]
That's because the default ExecutionStrategy that ships with graphql-java
does not support futures. You will get the same result if you define your
schema with just graphql-java.

**Comment by tristancaron** [comment]
So, what it is the right way to return a result coming from a database?

**Comment by oexza** [comment]
You can go all blocking by calling the get() function in the future or
use an async execution strategy implementation like this
https://github.com/bsideup/graphql-java-reactive, that way you can
return the future from the resolver and get all the reactive goodness.

**Comment by apottere** [comment]
Closing because this isn't an issue with graphql-java-tools.  @tristancaron feel free to comment if you have any more questions
