### ISSUE TITLE
Recursive input type breaks if wrapped in a list

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java-tools#36]
The following scenario seems to break:

```
type Query {
    allLinks(filter: LinkFilter): [Link]
}

input LinkFilter {
    OR: [LinkFilter!]
    description_contains: String
    url_contains: String
}
```

And the `LinkFilter` POJO:

```java
public class LinkFilter {

    private List<LinkFilter> OR;
    private String description_contains;
    private String url_contains;

    //getters & setters
}
```

The exceptions is:
> com.coxautodev.graphql.tools.SchemaClassScannerError: Two different classes used for type LinkFilter:
> \- class com.something.LinkFilter:
| parameter 0 of method public java.util.List com.something.Query.allLinks(com.something.LinkFilter)
> \- interface java.util.List:
| input object InputValueDefinition{name='OR', type=ListType{type=NonNullType{type=TypeName{name='LinkFilter'}}}, defaultValue=null, directives=[]}

If I unwrap the `OR` field to just a `LinkFilter`, everything is fine.

**Comment by apottere** [comment]
Ah, I think I forgot about lists in input types.  I'll apply the same
unwrapping logic to input fields

**Comment by kaqqao** [comment]
Bah, my PR doesn't really fix anything, so I closed it. If the query accepts a `List<LinkFilter>` directly, it doesn't get deserialized, and an instance of `List<LinkedHashMap>` is passed instead. I'm guessing the root cause is the same as the main issue described above.
