### ISSUE TITLE
Improved error messages

### ISSUE THREAD

**Issue by sazzer** [graphql-java/graphql-java-tools#38]
Currently when the resolvers are not wired up correctly the errors you get back tell you exactly what's wrong, and fixing it is easy.

However, if one of the graphqls files is invalid, you get a very cryptic antlr error that tells you nothing. I've had to resort to the debugger to find the line number in my file that is wrong and fix it that way.

**Comment by apottere** [comment]
The error messages from the parser itself aren't that great, so it might be good to open an issue on graphql-java for that.  This library should expose the full error message, though.
