### ISSUE TITLE
Support property lookup by field (not just methods)

### ISSUE THREAD

**Issue by konrad-garus** [graphql-java/graphql-java-tools#40]
I'd like to be able to use immutable data types, implemented as classes with public final fields like this:

```
public class Foo {
    public final String bar;

    public Foo(String bar) {
        this.bar = bar;
    }
}
```

However, right now graphql-java-tools seems to require `bar` to be a method or a getter (like `getBar()`).

I can work this around by adding a getter, but it's really noisy and messy:

```
public class Foo {
    public final String bar;

    public Foo(String bar) {
        this.bar = bar;
    }

    public String getBar() {
        return bar;
    }
}
```

**Comment by apottere** [comment]
This seems reasonable.  Should it only inspect final fields or any public field with that name?
