### ISSUE TITLE
IDL Modularisation 

### ISSUE THREAD

**Issue by oexza** [graphql-java/graphql-java-tools#42]
in graphql-java [](https://github.com/graphql-java/graphql-java/blob/master/docs/schema.rst#modularising-the-schema-idl) a type can be extended to add more fields but graphql-java-tools doesn't honor that. Check this example project https://github.com/oexza/graphql-java-tools-test you'll find that the Query type is extended in the Internal.graphqls file but introspection shows that it actually replaces the Query instead of just adding the field.

**Comment by apottere** [comment]
Yup, I realized this would be an issue a little while ago.  I'd like to update to graphql-java's own IDL wiring, but there's an api issue preventing me from doing that till 4.0.0 is released.  Is it ok if this waits on that?

**Comment by oexza** [comment]
Would it be too much work to eventually port to graphql-java's own IDL
wiring if this issue is resolved now? I want to create an Admin schema
which will have all the features of the public schema plus added
fields, interfaces, types etc. to support some backend features, and
so this issue is kinda like a blocker, I know I can duplicate the
schema but then that's an added maintenance overhead which is way less
than awesome. So yeah my answer is yes-ish it may be ok to wait.

**Comment by apottere** [comment]
No, it wouldn't make porting any more difficult, I was just hoping to avoid work.  It looks like graphql-java might be releasing an "alpha" 4.0.0 soon, but I think I might just implement extensions in the meantime.
