### ISSUE TITLE
Support for mismatched class and type names via annotations

### ISSUE THREAD

**Issue by sazzer** [graphql-java/graphql-java-tools#46]
I'm currently writing an app using this, and I'm having all of my GraphQL classes with slightly awkward names. For example, I already have an internal class called `User`, which stores rich types (e.g. the ID is a UserId, the Last Modified date is an Instant). As such, I've got the GraphQL representation of this called `UserModel`, which means that there are no typename clashes and things work cleaner.

Unfortunately this means that in my schema I've got UserModel as the name, instead of just User.

I know there is Dictionary support for renaming classes, but it would be useful if I could just annotate the class and have it work automatically.

For example, if I could define my user class as:

```kotlin
@GraphQLType("User")
data class UserModel(
        val id: String,
        val version: String,
        val updated: String,
        val name: String,
        val email: String?,
)
```

then I can refer to it as "User" throughout the schema, whilst the actual code has a different name and I never have to worry about the dictionary for these types.

**Comment by sazzer** [comment]
So - apparently this does already work without needing the annotation. Not sure how, and I'm not sure why it didn't for me before.

**Comment by apottere** [comment]
This is the major difference between 2.x and 3.x.  In 2.x, you had to provide all the classes you wanted to use and the name was derived from `.getClass().getSimpleName()`.  In 3.x, it actually scans all classes from the resolvers, and when it finds a method that matches a graphql field, it matches up the graphql field's return/argument types with classes used in those positions in the method.  Therefore, 3.x doesn't care what you call the java class `UserModel` as long as you use it for the graphql type `User` and nowhere else.
