### ISSUE TITLE
Allow generic custom generic types as return types of methods

### ISSUE THREAD

**Issue by abassouk** [graphql-java/graphql-java-tools#47]
In class `GenericType.RelativeTo`, the method `unwrapGenericType` has a list of Java types that should be considered wrappers, and the actual type is the first type parameter. I'd like to propose making this list configurable, as it's necessary for f.e. adapting reactive-streams return values. 

My personal use case was a reactive ExecutionStrategy that can fetch properties in parallel via RxJava; it works nicely (and fast), but it required modifying the above-mentioned class so that return types are recognized as the proper types. 

I don't trust yet my Kotlin knowledge to create a PR that implements this, and while admittedly it's a relatively niche requirement, it does make sense to have that type list generic.

**Comment by apottere** [comment]
Sounds good, I'll see what I can do.
