### ISSUE TITLE
Schema building fails if interfaces are not directly referred to

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java-tools#49]
I've received a complaint from someone trying to add interfaces to the [Link type from HowToGraphQL](https://www.howtographql.com/graphql-java/2-queries/). The example code is [here](https://github.com/gkarthics/graphql-example).

`Link` (an object type) has 2 interfaces: `LinkInterface` and `SecondInterface`. None of the interfaces are directly used in the schema i.e. all queries/mutations use `Link` directly.

What happens is that an error is thrown in [`SchemaClassScanner.kt:138`](https://github.com/graphql-java/graphql-java-tools/blob/3.2.1/src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt#L138), because `typeClass` for both interfaces is `null`, so `null` effectively becomes a duplicate key in the map ultimately causing an exception.

From my own experiments, if the interfaces are used directly e.g. I change the `allLinks` query to return `[LinkInterface]` instead of `[Link]`, everything is fine. I tried registering the interface classes directly via `SchemaParser#dictionary` but it doesn't make a difference.

**Comment by apottere** [comment]
Ah, I completely forgot to release my last round of changes, which included this fix (#45): https://github.com/graphql-java/graphql-java-tools/commit/72e6389b4b2cb2b806ff7b2ad88efeab22d4a55c.  I'll try to get this out today.

**Comment by kaqqao** [comment]
Ah, great! I'll close this one then. Thanks a bunch!

**Comment by gkarthics** [comment]
Wow! I guess this is the quickest turn around. 👍  Thank you so much.

**Comment by apottere** [comment]
@kaqqao @gkarthics `4.0.0` is syncing to central right now, feel free to try it out.  I still need to document some new things in the readme, but it should work for you.

**Comment by gkarthics** [comment]
@apottere  Hey Andy, I am not sure the issue I am facing now is because of this. But now I am having the "Invalid Schema" exception if I include Mutations.

**Comment by apottere** [comment]
@gkarthics what's the full error?

**Comment by gkarthics** [comment]
@apottere  Sorry that was a library mismatch in my local. But I do have a question, how can I query a list of Interfaces?
For example I have the schema definitions as below.

````
interface FirstInterface {
  id : ID!
}

type FirstImpl implements FirstInterface {
  id : ID!
  name : String
}
````


And I want a query like this
```
type Query {
    getInterfaces( Id : ID! ) : FirstInterface
}

```

 How can I achieve this with java, since the interfaces will not have any fields with it.
