### ISSUE TITLE
Issue while implementing an interface to another interface in the schema.graphqls

### ISSUE THREAD

**Issue by gkarthics** [graphql-java/graphql-java-tools#50]
I am trying to implement an interface to another interface as shown below.

```
interface SecondInterface {
	secondInterfaceValue : String
}

interface ThirdInterface implements SecondInterface {
	thirdInterfaceValue : String
}
```

And having the type implementing the `ThirdInterface` as below.

```
type ThirdImpl implements ThirdInterface {
	thirdInterfaceValue : String
	secondInterfaceValue : String
}

```

So with the above schema, if I run, I am facing the "`Invalid Schema`" exception.

**Comment by apottere** [comment]
Can you post the whole exception?

**Comment by kaqqao** [comment]
@apottere The schema is indeed invalid. It's trying to define an interface extending an interface, which is not allowed by the spec. I have already explained this to @gkarthics in Gitter, so he'll close the issue. Or you could as well.

**Comment by apottere** [comment]
Cool, I thought that might be the case but I'd never tried it so I wasn't sure it was invalid.

**Comment by gkarthics** [comment]
Yeah, sorry for expecting that. I will close this issue.
