### ISSUE TITLE
Usage of reflection reduces usefulness with Spring

### ISSUE THREAD

**Issue by martin-walsh** [graphql-java/graphql-java-tools#53]
If the lookup of `Query`, `Mutation` were not by `class.getSimpleName()` and instead by either annotation or interface/parent type, it would allow the Query class etc to be enhanced by Spring for validation, security, etc

Unfortunately, any attempt to do this now will fail as the proxy class generated by Spring etc will have a different name...

**Comment by apottere** [comment]
Check out the latest version - Root query resolvers are now indicated solely by annotation and can be spread across multiple resolvers.

**Comment by apottere** [comment]
https://github.com/graphql-java/graphql-java-tools/blob/master/README.md#root-resolvers

**Comment by martin-walsh** [comment]
Cool.  Will test it out.

**Comment by apottere** [comment]
@martin-walsh did that fix your issue?

**Comment by martin-walsh** [comment]
Works a treat, nice one !
