### ISSUE TITLE
Input Objects GraphQLObjectType cannot be cast to GraphQLInputType

### ISSUE THREAD

**Issue by icer9955** [graphql-java/graphql-java-tools#56]
I'm following the example listed here:
https://github.com/graphql-java/graphql-java-tools#input-objects

However, when I try to launch the app, I get the following error:
```plain
graphql.schema.GraphQLObjectType cannot be cast to graphql.schema.GraphQLInputType
```

This is basically what I've done:
```java
class Query implements GraphQLQueryResolver {
    public int add(AdditionInput input) {
        return input.getFirst() + input.getSecond();
    }
}

class AdditionInput {
    private int first;
    private int second;
    
    // getFirst()
    // setFirst()
    // getSecond()
    // setSecond()
}
```

Am I missing something?  Do I need to implement some interface on `AdditionInput`?  Or is this a bug?

**Comment by apottere** [comment]
This seems like a bug, I'll have to dig in and figure out what's going on.  Do you have a more complete stacktrace?

**Comment by apottere** [comment]
And what does your schema look like?

**Comment by icer9955** [comment]
Derp, after digging into the schema I found it:

```plain
type AdditionInput {
  first: Int,
  second: Int,
}
```

Should actually be:
```plain
input AdditionInput {
  first: Int,
  second: Int,
}
```

**Comment by apottere** [comment]
I was thinking that might be the case, but I wasn't sure.  It's a bug regardless, it should have a more descriptive error instead of a class cast exception.
