### ISSUE TITLE
Restore support for generics in Inputs & Types

### ISSUE THREAD

**Issue by martin-walsh** [graphql-java/graphql-java-tools#57]
requireRawClass() function added in https://github.com/graphql-java/graphql-java-tools/commit/bc9160d9827caa0e8d5613458533fe8be49e9ad1 removes the ability to use generics to capture whether a field was posted or not when binding requests.

Example

```
class OptionalInput<T> {

    private boolean _set = false
    private T value

    void set(T value) {
        this._set = true
        this.value = value
    }

    T get() {
        return this.value
    }

    boolean isSet() {
        return this._set
    }
}
class SomeInput {
    final OptionalInput<String> name = new OptionalInput<String>()

    // The below setter are required for binding from the mutation request.

    void setName(String name) {
        this.name.set(name)
    }
}

class Mutation {
    Object updateName(SomeInput someInput)  {

        if (someInput.name.isSet()) {
            String name = someInput.name.get()
            // Do something as the data was posted
        } else {
            // Do nothing as not posted.  Otherwise Java String would be null and we would erroneously clear a value
        }
    }
}
```

**Comment by apottere** [comment]
`java.util.Optional` should be supported for nullable field arguments, so you shouldn't need to re-implement that.  The `SchemaParserOptions` also allow you to define your own generics that should be unwrapped to find the "real" type: https://github.com/graphql-java/graphql-java-tools/blob/master/src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt#L177

**Comment by apottere** [comment]
@martin-walsh is this fixed?

**Comment by martin-walsh** [comment]
Hi,

Getting back to my project again...

Unfortunately I can't leverage `java.util.Optional` as I need to accept null as a value, however yes adding a GenericWrapper via the SchemaParserOptions works perfectly
