### ISSUE TITLE
Better Kolin support

### ISSUE THREAD

**Issue by jdorleans** [graphql-java/graphql-java-tools#65]
Do you have any plans to add a better support to Kotlin? I'd love to help if necessary. It's a bit annoying having to rely on converting some data to java like from KClass to Class.

**Comment by apottere** [comment]
Do you mean in the builder?  I can definitely add methods that take `KClass`.

**Comment by jdorleans** [comment]
Well, the builder and any other possible place. I'm not very familiar with your lib yet, but my first impression was we could have some improvements to make it more KT oriented when using the lib.
