### ISSUE TITLE
partial results with errors

### ISSUE THREAD

**Issue by rolandkozma** [graphql-java/graphql-java-tools#72]
Hi,

graphql-java docs states that graphql allows partial results with errors.
So if I have a query defined in graphql schema like this: 

getUser(id: Long!): User

type User {
    username: String
    company: Company
}

How can I have separate resolvers for username and company fields?
If the company resolver fails, I'd still like to get the username in the response. 
Also an error should be present in the errors list for the company resolver failure.

Is there a difference between DataFetchers and Resolvers? (I'm a bit confused with these terms)

Thanks,
-Roland

**Comment by apottere** [comment]
This library just creates data fetchers for graphql-java, so anything that graphql-java does should still apply.

**Comment by apottere** [comment]
This library has a concept of "Resolvers", but really under the covers it's just creating seperate data fetchers for each graphql field that call a certain method on a resolver using reflection.

**Comment by rolandkozma** [comment]
Thanks for your answer, but it's still not clear for me how to implement the behaviour I described. 
Could you help me please? 
I'm also thinking about a similar scenario when a user has rights to access just some fields from a type while other fields are forbidden to him. 
If also forbidden fields are requested in a query, instead of failing the entire request, I'd still like to return the accessible fields and have some errors describing the reason why the forbidden fields weren't able to be accessed.

**Comment by apottere** [comment]
Have you tried doing what you're describing?  I don't see why it wouldn't work.  If it doesn't work, comment with what happened and how it didn't work as expected.

**Comment by rolandkozma** [comment]
For the "getUser(id: Long!): User" query, I described in the first post, in Java I have:

@Component
public class UserQuery implements GraphQLQueryResolver {
    public UserOutput getUser(long id) {
      // resolve username...
      // resolve company...
      // return output with successfully resolved fields and errors for unresolved fields
    }
}

If an exception is thrown, the flow ends with ExceptionWhileDataFetching GraphQLError. 
The returned data will be null and in errors I'll have the failure reasons (as handled in my custom GraphQLErrorHandler).

Because I want to have the fields which were successfully resolved in the response I can use try-catch on each step in order to not let an exception to end the flow. In this way I can populate my UserOutput object with only the successfully resolved fields.
I can also collect a list of errors/exceptions for the fields that failed to be resolved.

But I haven't found a way to return both the data and the errors all together.
How can I do this?

Thanks,
Roland

**Comment by apottere** [comment]
I think what you really want is a custom `ExecutionStrategy`.  graphql-java-tools just creates data fetchers, it doesn't specify what happens when they fail.

**Comment by rolandkozma** [comment]
Thanks for the hint. Which is the default ExecutionStrategy implementation used by graphql-java-tools and how can I replace it with my own implementation?
