### ISSUE TITLE
Support generic types

### ISSUE THREAD

**Issue by oliemansm** [graphql-java/graphql-java-tools#75]
What are your thoughts on adding support for generic types? Our current problem is pagination and the fact we need to copy paste a lot of the same code because it's not supported at the moment (unless we're overlooking something?). If we ever want to change our base `Connection` type, we would have to change a lot of code just because generics isn't supported.

This issue was raised here as well: https://github.com/facebook/graphql/issues/190. Basically the same use case, but it's still open. They did mention that the JS version of graphql-tools supports a way to have the connection and edges generated for a specific type:
```
type MyType {
  hello: String
  world: String
}

${ connectionAndEdgeFor('MyType') }
```

In my opinion this should be supported in some way, preferrably as pure generics, because that gives a lot more flexibility for other use cases as well. Then we could do something like:
```
type Connection<T> {
  pageInfo: PageInfo!
  edges: [Edge<T>]
  totalCount: Int
  nodes: [T]
}

type Edge<T> {
  node: T
  cursor: String!
}
```
Is this something that could be added to the library?

**Comment by apottere** [comment]
The GraphQL schema language comes straight from graphql-java, so you'd have to open an issue there for supporting generics in the schema.  Generally that library tries to follow the reference implementation as closely as possible, so anything that graphql-js implements graphql-java will likely implement at some point.

As far as relay support goes, it would be possible to have graphql-java-tools support a special decorator (like `@relayConnection`) on a type that would tell it to generate a connnection and edge for that type when creating the schema.

**Comment by oliemansm** [comment]
Ok thanks, I'll think of something.
