### ISSUE TITLE
Modular GraphQL with Schema stitching

### ISSUE THREAD

**Issue by k-komarov** [graphql-java/graphql-java-tools#76]
Have you considered to implement this feature?
https://de.slideshare.net/sashko1/modular-graphql-with-schema-stitching

**Comment by apottere** [comment]
I've thought about doing something similar to that, but I don't know if this project would be the right place for it;  I think it might work better in a separate project.  It's a really cool idea, though, so I'd be interested in taking a stab at it.

**Comment by jameskleeh** [comment]
@apottere Why don't you think this project would be the right place? The schema stitching for apollo is in https://github.com/apollographql/graphql-tools/tree/master/src/stitching
