### ISSUE TITLE
Field deprecation via schema using directive @deprecated

### ISSUE THREAD

**Issue by acidbluebriggs** [graphql-java/graphql-java-tools#8]
There doesn't seem to be a way to publish deprecated messages for Fields/Enums.  There is an implementation of a **@deprecated** directive added to the graphql-js implementation found [At this merge](https://github.com/graphql/graphql-js/pull/384). Could we add this processing to the **SchemaParser.kt** class so we can deprecate via the schema?

I'm currently working on adding this and was wondering if there were any issues you might have with this? I noticed on the [README.md for 3.0](https://github.com/graphql-java/graphql-java-tools/blame/graphql-java-3.0/README.md#L273) that the **@doc** directive seems to have been removed. Is there a reason for this? Are directives being removed completely? If so, how are we going to be able to deprecate fields/enums in the schema?

**Comment by apottere** [comment]
This would be a great addition - directives aren't being removed, the @doc directive was just a workaround till the ANTLR parser supported saving comments (which is coming in graphql-java 3.0).

**Comment by acidbluebriggs** [comment]
Cool, I'll get going. Thanks!
