### ISSUE TITLE
error handling in custom scalar type deserialization

### ISSUE THREAD

**Issue by rolandkozma** [graphql-java/graphql-java-tools#81]
If an exception happens to be thrown while handling deserialization of a scalar type in:
        I parseValue(Object input);     or      I parseLiteral(Object input);
 methods from the Coercing<I, O> interface, 
it is not handled and the output of the query will be an empty String, as "".

Going on the flow I found that in graphql.GraphQL.executeAsync(ExecutionInput) there is a catch that catches AbortExecutionException so I made the exception that I throw at scalar deserialization to extend AbortExecutionException in order to be caught. With this fix, the exception will be passed in my custom GraphQLErrorHandler and something meaningful will be displayed.
However there is no way to collect the path/name of the field that failed to be deserialized and it would be great to have one.
I'm not sure, but I think that exceptions like CoercingParseValueException may be considered clientErrors and automatically handled by the framework. What do you think?

Thanks,
Roland

**Comment by apottere** [comment]
This seems like an issue more for the servlet or graphql-java itself.  I'm not sure how graphql-java expects to handle errors in coercion or if it needs to be updated to support that exception

**Comment by rolandkozma** [comment]
Should I log the issue on graphql-java repo then?

**Comment by apottere** [comment]
Yeah, I would open an issue in graphql-java if you haven't already.

**Comment by rolandkozma** [comment]
I haven't opened it.
