### ISSUE TITLE
SchemaClassScanner warnings

### ISSUE THREAD

**Issue by JuanCarlosGonzalez** [graphql-java/graphql-java-tools#85]
Hi.

First of all, thanks for this library. It's a great complement for graphql-java.

I have a strange behaviour related to SchemaClassScanner warnings:

My schema:

> type Query {
>     # Service from its id
>     service(serviceId: String!): Service
>     # Infrastructure service from its id
>     serviceInfrastructure(serviceId: String!): ServiceInfrastructure
> }
> 
>
> type Mutation {
>     createService(name: String!): Service
>     updateServiceInfrastructure(serviceId: String!, serviceInfrastructure: ServiceInfrastructureInput!): ServiceInfrastructure
> }
> 
> interface Service {
>     id: String!
>     name: String!
>     version: String!
> }
> 
> type ServiceV1 implements Service {
>     id: String!
>     name: String!
>     version: String!
> }
> 
> interface ServiceInfrastructure {
>     serviceId: String!
>     version: String!
> }
> 
> type ServiceInfrastructureV1 implements ServiceInfrastructure {
>     serviceId: String!
>     httpProxyLambdaArn: String!
>     graphQLCommandAdapterLambdaArn: String!
>     graphQLQueryAdapterLambdaArn: String!
>     commandExecutorLambdaArn: String!
>     materializationLambdaArns: [String]
>     eventStoreTableArn: String!
>     eventPumpLambdaArn: String!
>     eventStreamArn: String!
>     commandStreamArn: String!
>     commandStreamProcessorLambdaArn: String!
>     serviceEventSubscriptions: [ServiceEventSubscription]
>     version: String!
> }
> 
> input ServiceInfrastructureInput {
>     serviceId: String!
>     httpProxyLambdaArn: String!
>     graphQLCommandAdapterLambdaArn: String!
>     graphQLQueryAdapterLambdaArn: String!
>     commandExecutorLambdaArn: String!
>     materializationLambdaArns: [String]
>     eventStoreTableArn: String!
>     eventPumpLambdaArn: String!
>     eventStreamArn: String!
>     commandStreamArn: String!
>     commandStreamProcessorLambdaArn: String!
>     serviceEventSubscriptions: [ServiceEventSubscriptionInput]
> }
> 
> input ServiceEventSubscriptionInput {
>     sourceServiceId: String!
>     eventProcessorLambdaArn: String!
> }
> 
> interface ServiceEventSubscription {
>     sourceServiceId: String!
>     eventProcessorLambdaArn: String!
>     version: String!
> }
> 
> type ServiceEventSubscriptionV1 implements ServiceEventSubscription {
>     sourceServiceId: String!
>     eventProcessorLambdaArn: String!
>     version: String!
> }

When my service starts I get the following warnings:
2017-10-23 14:00:54 <> WARN  SchemaClassScanner:114 - Dictionary mapping was provided but never used, and can be safely deleted: "ServiceV1" -> cloud.plexo.platform.region.resources.client.model.ServiceV1
2017-10-23 14:00:54 <> WARN  SchemaClassScanner:114 - Dictionary mapping was provided but never used, and can be safely deleted: "ServiceInfrastructureV1" -> cloud.plexo.platform.region.resources.client.model.metadata.ServiceInfrastructureV1
2017-10-23 14:00:54 <> WARN  SchemaClassScanner:114 - Dictionary mapping was provided but never used, and can be safely deleted: "ServiceEventSubscriptionV1" -> cloud.plexo.platform.region.resources.client.model.metadata.ServiceEventSubscriptionV1
2017-10-23 14:00:54 <> WARN  SchemaClassScanner:138 - Schema type was defined but can never be accessed, and can be safely deleted: ServiceV1
2017-10-23 14:00:54 <> WARN  SchemaClassScanner:138 - Schema type was defined but can never be accessed, and can be safely deleted: ServiceInfrastructureV1
2017-10-23 14:00:54 <> WARN  SchemaClassScanner:138 - Schema type was defined but can never be accessed, and can be safely deleted: ServiceEventSubscription
2017-10-23 14:00:54 <> WARN  SchemaClassScanner:138 - Schema type was defined but can never be accessed, and can be safely deleted: ServiceEventSubscriptionV1

However, if I include an additional query for un unrelated type, no warning is generated. The modified schema is:

> type Query {
     **dummy(id: String!): Dummy**
>     service(serviceId: String!): Service
>     serviceInfrastructure(serviceId: String!): ServiceInfrastructure
> }
> 
> type Mutation {
>     createService(name: String!): Service
>     updateServiceInfrastructure(serviceId: String!, serviceInfrastructure: ServiceInfrastructureInput!): ServiceInfrastructure
> }
> 
> interface Service {
>     id: String!
>     name: String!
>     version: String!
> }
> 
> type ServiceV1 implements Service {
>     id: String!
>     name: String!
>     version: String!
> }
> 
> interface ServiceInfrastructure {
>     serviceId: String!
>     version: String!
> }
> 
> type ServiceInfrastructureV1 implements ServiceInfrastructure {
>     serviceId: String!
>     httpProxyLambdaArn: String!
>     graphQLCommandAdapterLambdaArn: String!
>     graphQLQueryAdapterLambdaArn: String!
>     commandExecutorLambdaArn: String!
>     materializationLambdaArns: [String]
>     eventStoreTableArn: String!
>     eventPumpLambdaArn: String!
>     eventStreamArn: String!
>     commandStreamArn: String!
>     commandStreamProcessorLambdaArn: String!
>     serviceEventSubscriptions: [ServiceEventSubscription]
>     version: String!
> }
> 
> input ServiceInfrastructureInput {
>     serviceId: String!
>     httpProxyLambdaArn: String!
>     graphQLCommandAdapterLambdaArn: String!
>     graphQLQueryAdapterLambdaArn: String!
>     commandExecutorLambdaArn: String!
>     materializationLambdaArns: [String]
>     eventStoreTableArn: String!
>     eventPumpLambdaArn: String!
>     eventStreamArn: String!
>     commandStreamArn: String!
>     commandStreamProcessorLambdaArn: String!
>     serviceEventSubscriptions: [ServiceEventSubscriptionInput]
> }
> 
> input ServiceEventSubscriptionInput {
>     sourceServiceId: String!
>     eventProcessorLambdaArn: String!
> }
> 
> interface ServiceEventSubscription {
>     sourceServiceId: String!
>     eventProcessorLambdaArn: String!
>     version: String!
> }
> 
> type ServiceEventSubscriptionV1 implements ServiceEventSubscription {
>     sourceServiceId: String!
>     eventProcessorLambdaArn: String!
>     version: String!
> }
> 

**type Dummy {**
     **id: String!**
**}**

Thanks in advance.

**Comment by apottere** [comment]
Could you try with `4.2.0`?  This might be fixed in that version.

**Comment by rsmkrishna** [comment]
I am also coming across same scenario, i am using version 6.0. any help?

**Comment by apartensky** [comment]
I'm seeing the same issue with nested input types. Having to create dummy queries to get the schema to parse. I'm running graphql-java-tools 4.3.0 and graphql-java 6.0.

**Comment by oliemansm** [comment]
I'm closing this one, since the main issue seems to be duplicated in the more active issue #77
