### ISSUE TITLE
Are subscriptions supported?

### ISSUE THREAD

**Issue by karl-run** [graphql-java/graphql-java-tools#88]
If yes, would it be possible to get an example implementation in the docs?

**Comment by apottere** [comment]
I'm actually working on that right now, so I should have an example tomorrow sometime.

**Comment by karl-run** [comment]
That's great! Looking forward to it.

**Comment by apottere** [comment]
It might take a little while to get the servlet and spring-boot start working to have a real example, but subscriptions might be working if you return a `Publisher` from the resolver method.  Once I have a real example I'll update the docs.

**Comment by karl-run** [comment]
I'm playing around with the concept now. By `Publisher` do you mean a reactive-streams `Publisher`?

**Comment by karl-run** [comment]
I'm looking at [this example](https://github.com/graphql-java/graphql-java-subscription-example) to get an idea. If I return a `Publisher` from the `GraphQLSubscriptionResolver` I get the following error:

`Failed to instantiate [com.coxautodev.graphql.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is com.coxautodev.graphql.tools.SchemaClassScannerError: Unable to match type definition (NonNullType{type=ListType{type=TypeName{name='Person'}}}) with java type (org.reactivestreams.Publisher<java.util.List<com.fmcti.dsi.scale.person.Person>>): Java class is not a List or generic type information was lost: org.reactivestreams.Publisher<java.util.List<com.fmcti.dsi.scale.person.Person>>`

My data object is a `Person` of which I'm trying to return a list. This is probably me doing something wrong. Any ideas?

**Comment by apottere** [comment]
@karl-run are you using `4.2.0`?  It won't work in previous versions.  If you are, it looks like you're using it correctly so I'll have to add some more cases to the tests.

**Comment by karl-run** [comment]
Oh.. I was on 4.1.2. When I use the right version it starts but I get some other errors - but those are probably related to me not knowing how to use reactive-streams. I'll play around some more.

**Comment by bulka777** [comment]
Interesting...I am getting a serialization issue if I return a Flowable. Am I missing something?

**Comment by jamesmmchugh** [comment]
@apottere Any news on when that example will be ready?

**Comment by greenled** [comment]
@jamesmmchugh looks like branch `subscription-support` is the example WIP. Am I right @apottere ?

**Comment by jamesmmchugh** [comment]
@greenled thanks for pointing that out. Tried copying the changes from that branch and it seems to work functionally (i.e. doesn't crash), but seems to deliver the subscription over HTTP rather than upgrading to websocket connection - so you don't actually receive any updates. I guess the websocket servlet needs to be hooked in somehow to the graphql config, but it's not obvious how to do this from the docs.

**Comment by Syl1234** [comment]
I guess I have the same problem. While requesting with curl with correct header "Accept:text/event-stream", i don't have any update, only {"data":{}}. I'm currently using the branch subscription-support. 

Any advice in order to work properly with subscription ?

**Comment by greenled** [comment]
I recently implemented subscriptions with graphql-java-tools 4.3 and graphql-java 7.0 for a real-time chat app. I am not using Spring, but Play! Framework 1.5.0.

Anyway, this library is framework-agnostic so, [by the book](https://github.com/graphql-java/graphql-java/blob/master/docs/subscriptions.rst): make the resolver return a Publisher<YourObject>, and expect a Publisher<ExecutionResult> from executionResult.getData() after executing the query.

@Syl1234 Pay atention to the graphql-java version you use, as there is a bug in 6.0 that removes the root node from subscription results. If you just add a dependency on graphql-java-tools 4.3, it will use graphql-java 6.0 by default, so you will need to explicitly add a dependency on graphql-java 7.0.

**Comment by Syl1234** [comment]
@greenled Thx for tips. I'll give a try to your advice asap. As you managed to use subscriptions, do you know if i have to deal with transport layer (ie dealing with websocket for example) at server level ?

**Comment by jamesmmchugh** [comment]
I think your issue is the same as mine - and the question is in the wrong repo. As @greenled said, graphql itself is framework agnostic. The question should be asked in either graphql-spring-boot repo or graphql-java-servlet repo (which is auto configured by the former). I've had a look at them and they don't seem to contain anything relevant to websocket upgrades, so yes it looks like this will have to be manually managed as per the example branch in this repo.

**Comment by greenled** [comment]
@Syl1234 in my cacase, the framework handles protocol upgrades. Again, graphql-java-tools just wires your resolvers serverside to help you get a `Publisher<YourObject>`. Whatever you do with that Publisher is up to you and the framework you are using.

**Comment by ccamel** [comment]
@greenled Unfortunately, I did not manage to make it work.

I'm using the following versions:
- `graphql-spring-boot`: 5.0.2
- `graphiql-spring-boot`: 5.0.2
- `graphql-java-tools`: 5.2.4
- `rxjava`: 2.2.2

Here's the minimal graphql subscription resolver I wrote for testing:
```java
public class FooSubscriptionResolver implements GraphQLSubscriptionResolver {
    public Publisher<Foo> getFoos() {
        return Flowable.fromArray(
                Foo.create("a"),
                Foo.create("b"),
                Foo.create("c")
        );
}
```
Schema is following (for the subscription side):

```graphql
type Subscription {
    foos: Foo!
}
```

When doing the following subscription (from the graphiql editor):
```
subscription {
  foos {
    label
  }
}
```

Then I get the following stack trace (root cause):
```java
Caused by: com.coxautodev.graphql.tools.ResolverError: Expected source object to be an instance of 'com.foo.Foo' but instead got 'io.reactivex.internal.operators.flowable.FlowableFromArray'
	at com.coxautodev.graphql.tools.FieldResolver$getSourceResolver$2.invoke(FieldResolver.kt:27) ~[graphql-java-tools-5.2.4.jar:na]
	at com.coxautodev.graphql.tools.FieldResolver$getSourceResolver$2.invoke(FieldResolver.kt:10) ~[graphql-java-tools-5.2.4.jar:na]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:144) ~[graphql-java-tools-5.2.4.jar:na]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:258) [graphql-java-9.2.jar:na]
	... 46 common frames omitted
```

It seems that `graphql-java-tools` did not expect to have a `Publisher` ?

I don't understand what I'm doing wrong... Any help is welcome. Thanks.

**Comment by assafberg** [comment]
@ccamel did you set the subscription execution strategy (to SubscriptionExecutionStrategy)?

**Comment by ccamel** [comment]
@assafberg Yes !!! You got it ! Many thanks ! :smile: Now it works like a charm.

**Comment by pillarguo** [comment]
> @assafberg Yes !!! You got it ! Many thanks ! 😄 Now it works like a charm.

can you paste your FooSubscriptionResolver.getFoos() ? Mine didn`t get work. 

>`    public Publisher<EventDevices> eventDevices(String name){
        UnicastProcessor<EventDevices> processor = UnicastProcessor.create();
        FluxSink<EventDevices> sink = processor.sink(FluxSink.OverflowStrategy.IGNORE);
        List<EventDevices> eventDeviceses =new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            EventDevices eventDevices = new EventDevices();
            eventDevices.setEventId(i);
            eventDevices.setId(i+100);
            eventDevices.setName("namama");
            eventDeviceses.add(eventDevices);
        }
        eventDeviceses.stream().forEach(eventDevices -> {
            sink.next(eventDevices);
        });
        return processor;
    }`
