### ISSUE TITLE
No class found for type implementing known interface

### ISSUE THREAD

**Issue by oliemansm** [graphql-java/graphql-java-tools#97]
I've got the following (partial) schema:

```
type FilterSettings {
  id: ID!
  filterFields: [FilterField!]!
}

interface FilterType {
  id: ID!
  label: String!
}

type MultipleSelectFilterType implements FilterType {
  id: ID!
  label: String!
  options: [Option!]!
}

type Option {
  id: ID!
  label: String!
}
```

I've got a resolver that for this test does the following. This is the only place `FilterType` is returned.
```java
@Named
public class FilterFieldResolver implements GraphQLResolver<FilterField> {

  public List<FilterType> filterTypes(FilterField field) {
    MultipleSelectFilterType multipleSelectFilterType = new MultipleSelectFilterType("1", "1", "Cliëntmatch", null);
    return Arrays.asList(multipleSelectFilterType);
  }
}
```
It cannot instantiate `SchemaParser` because:
```
Caused by: com.coxautodev.graphql.tools.SchemaClassScannerError: Object type 'MultipleSelectFilterType' implements a known interface, but no class could be found for that type name.  Please pass a class for type 'MultipleSelectFilterType' in the parser's dictionary.
```
When I try to explicitly add the class to the dictionary using 
```java
@Bean
public SchemaDictionary dictionary() {
  return new SchemaDictionary().add(MultipleSelectFilterType.class);
}
``` 
it complains that the class already exists in the dictionary when starting up.

I've also tried adding dummy methods to query a `MultipleSelectFilterType` by id directly, but that doesn't help either. 

This effect can also been seen if you delete the `human` method in the schema in the example project:
```
type Query {
    # If episode omitted, returns the hero of the whole saga. If provided, returns the hero of that particular episode
    hero(episode: Episode): Character
#    # Find human by id
#    human(id: String!): Human
#    # Find droid by id
    droid(id: String!): Droid
    # Find character by id
    character(id: String!): Character
}
```
In that case it will give the same error about `Human`. When you uncomment the method it works again. But if I try this technique within my own project it still doesn't work.

My Java `MultipleSelectFilterType` class also actually implement the `FilterType` interface, and are named exactly the same as in the schema. Everything else seems to be working fine, so really no clue what I'm missing here.

How can I solve this problem?

**Comment by oliemansm** [comment]
I'm getting a bit further now, but feels still a bit unstable. I had to remove the `implements FilterType` part, and keep my dummy `multiSelectFilterType: MultiSelectFilterType` query to ensure the `SchemaParser` was aware of that class. Starting the app then succeeded, but GraphQL didn't know that `MultiSelectFilterType` implemented `FilterType` because I had removed that part. It wouldn't start earlier though keeping that part.

Now if I add it again it does start! But as soon as I change something completely different and I start running in the same Exception, I have to do this trick again. So remove that `implements FilterType`, start the app, and then add that part again and restart the app. And then hope I don't have to change anything else, because it feels like it might break at any time...

So any solution which is more stable and doesn't require those dummy queries, that I don't need myself, but are only required for the parser would be much appreciated.

**Comment by apottere** [comment]
Yeah, that sounds like a bug in the library.  I'll take a look and see if I can reproduce it in a test.

**Comment by oliemansm** [comment]
I've added a small test in my fork to show how I'd like to use it. See: https://github.com/oliemansm/graphql-java-tools/commit/e2eb4db70596c7a132df6557f55af393751ba356. Using this test I can make it work by explicitly adding the implemenation using `SchemaParser.newParser().dictionary(InterfaceImplementation.NamedResourceImpl.class)`. The test I've created here intentionally fails just the way it was doing in my case. 

Does this test represent the bug you want to find and solve, or are you referring to the fact that when explicitly adding the implementation class to the dictionary using the spring boot example it complains that it already knows that class? While without it, it won't start showing the same exception as the above test.

**Comment by oliemansm** [comment]
Any news on this issue? Just had to switch branches and got the same error again. So had to remove the `implements FilterType` in de `graphqls` file, started the app just fine, then added the `implements FilterType` again and now it starts without problem. Such a weird issue.

**Comment by oliemansm** [comment]
I've added two tests to graphql-spring-boot-autoconfigure (see: https://github.com/oliemansm/graphql-spring-boot/blob/issue/97-no-type-found-for-interface/graphql-spring-boot-autoconfigure/src/test/java/com/oembedler/moon/graphql/boot/test/graphqlJavaTools/GraphQLJavaToolsAutoConfigurationTest.java). To be able to do this I refactored the autoconfigure class a bit by adding a `SchemaStringProvider` so I could I tests with manual schema strings instead of having it pick up the `.graphqls` resources automatically.

The strange thing is that in this case it works as expected. I added the implementation class to the dictionary the same way I did in my real project, but in this case it didn't complain it was already in there, but successfully starts. I've tried it using a simple schema and one with a deeper hierarchy involving another resolver. Both cases just work as they should...

Any idea in which direction to look now?

**Comment by oliemansm** [comment]
All the problems I'm encountering are caused by the `dictionary.containsKey(type)` check in the `handleInterfaceOrUnionSubTypes` method. That check somehow in my case doesn't correctly recognize that it is in fact in the dictionary. I could solve it by explicitly filtering the dictionary keys with my own check and seeing if the resulting list is not empty. That works.

There was also one use of `distinct()` that didn't work properly (as in, it wasn't actually removing duplicates from the list). Modified that one to `distinctBy(name)`.

I'll submit a pull request. Can you double check and merge it so we can switch back instead of using our own build for now?

**Comment by schmidt-uni-leipzig** [comment]
I do not think, that this issue is solved. I tested it against the latest commit in the repository and the error still apprears.

In the following snippet, the childOne and childTwo queries must be declared. Otherwise, I get an exception like this:

`com.coxautodev.graphql.tools.SchemaClassScannerError: Object type 'ChildOne' implements a known interface, but no class could be found for that type name.  Please pass a class for type 'ChildOne' in the parser's dictionary.
	at com.coxautodev.graphql.tools.SchemaClassScanner.handleInterfaceOrUnionSubTypes(SchemaClassScanner.kt:200) ~[classes/:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:87) ~[classes/:na]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:149) ~[classes/:na]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:155) ~[classes/:na]`

```
schema {
    query: Query
}

type Query {
    bases: [Base]
    # this query must be included as dummies
    childOne: [ChildOne]
    # this query must be included as dummies
    childTwo: [ChildTwo]
}

interface Base {
    text: String
}

type ChildOne implements Base {
    text: String
}

type ChildTwo implements Base {
    text: String
}

```

**Comment by oliemansm** [comment]
This issue doesn't "fix" autodiscovery, but instead fixes the problem that adding these classes to the dictionary didn't work. In your case instead of adding these methods, you can add the classes to the dictionary like this.
```java
  @Bean
  public SchemaParserDictionary schemaParserDictionary() {
    return new SchemaParserDictionary()
        .add(ChildOne.class)
        .add(ChildTwo.class);
  }
```
Then you don't need to add those dummy methods.

**Comment by schmidt-uni-leipzig** [comment]
@oliemansm Thank you for your replay. In the meantime, I a lready implemented the dictionary as recommended. 

But I think, this aproach is a quick hack only.  Are you going to re-open this issues again to inspect the origin "bug"? Or would you like to recommend your approach officially? In total, the graphql implementation shall scan for implementations of an interface, altough it is not used in a query directly. The method bases : [Base] relates to to ChildOne as well as ChildTwo.

**Comment by oliemansm** [comment]
@schmidt-uni-leipzig I believe I've seen other issues about that here as well, and from what I recall autodiscovery of the implementations of interfaces like the way we want it currently simply isn't implemented. So I think it's more of a feature request than a bug actually. Perhaps open up a new issue for that linking to this issue to request it? I don't have the time at the moment to take a look at that myself, but maybe @apottere or someone else has time to look into it.

**Comment by MLNW** [comment]
> 
> 
> I do not think, that this issue is solved. I tested it against the latest commit in the repository and the error still apprears. @apottere Please open this issue again.
> 
> In the following snippet, the childOne and childTwo queries must be declared. Otherwise, I get an exception like this:
> 
> `com.coxautodev.graphql.tools.SchemaClassScannerError: Object type 'ChildOne' implements a known interface, but no class could be found for that type name. Please pass a class for type 'ChildOne' in the parser's dictionary. at com.coxautodev.graphql.tools.SchemaClassScanner.handleInterfaceOrUnionSubTypes(SchemaClassScanner.kt:200) ~[classes/:na] at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:87) ~[classes/:na] at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:149) ~[classes/:na] at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:155) ~[classes/:na]`
> 
> ```
> schema {
>     query: Query
> }
> 
> type Query {
>     bases: [Base]
>     # this query must be included as dummies
>     childOne: [ChildOne]
>     # this query must be included as dummies
>     childTwo: [ChildTwo]
> }
> ```

I just had the same problem. After adding the dummy queries everything works .. Is there any other way to solve this?
