### ISSUE TITLE
Root query resolver warnings in 4.3.0

### ISSUE THREAD

**Issue by rolandkozma** [graphql-java/graphql-java-tools#99]
After I upgraded from 4.1.2 to version 4.3.0, I noticed in the logs that a warning log appears for each of my resolver classes, although everything still seems to work well in the project.

Resolvers:

    @Component
    public class Query implements GraphQLQueryResolver {
    ...
    }

    @Component
    public class Mutation implements GraphQLMutationResolver {
    ...
    }

Logs:

Root query resolver was provided but no methods on it were used in data fetchers for GraphQL type 'Query'!  Either remove the com.coxautodev.graphql.tools.GraphQLQueryResolver interface from the resolver or remove the resolver entirely: com.omniacasino.omniawebapi.graphqlresolver.Query@67c9307b

Root mutation resolver was provided but no methods on it were used in data fetchers for GraphQL type 'Mutation'!  Either remove the com.coxautodev.graphql.tools.GraphQLMutationResolver interface from the resolver or remove the resolver entirely: com.omniacasino.omniawebapi.graphqlresolver.Mutation@63348881

Please help me to understand the cause of the warning and how to fix it correctly. I can't understand the part: "no methods on it were used in data fetchers for GraphQL type 'Mutation'/'Query'"

Thanks,
Roland

**Comment by KammererTob** [comment]
Can confirm. This might be related to https://github.com/graphql-java/graphql-java-tools/issues/22 since the warning disappears when i remove my `@PreAuthorize("hasAnyRole('...')")` annotation. 
Might not yet be released?
